Introduce work_queue package and new bindings
This directory will be the future home of Work Queue, once we clean up stuff...

- Use SWIG to generate PERL5 and Python bindings
    - SWIG will generate a direct 1-to-1 binding for w/e language you wish...
      we are currently supporting PERL5 and Python.
    - These bindings, however, may not match the idioms of the target language,
      so a higher-level interface may be desirable.  I made one for Python.

- The new Python bindings are mostly compatible with the old python-workqueue,
  except for the following changes:

    1. Name changes:

	workqueue module is now work_queue
	specify_input_buffer method is now specify_buffer
	task.taskid attribute is now task.id

    2. No longer support direclty modifying object attributes

	task.tag = "foo" # No longer allowed

       Instead, use specify_* methods.
       This is for compatibility with Python 2.4.

- Python bindings are also documented and now show up in doxygen API.

- configure will now detect PERL5 and Python and will determine whether or not
  to build those bindings.

- TODO:
    - Remove old python-workqueue bindings.
    - Add install targets for bindings.
    - configure should also detect swig.
    - More documentation for bindings.
    - More rigurous testing.
    - PERL binding example, documentation, tests, etc.


git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@1536 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -32,6 +32,7 @@ case "$build_cpu" in
 	;;
 esac
 
+include_package_work_queue="work_queue"
 include_package_sand="sand"
 include_package_allpairs="allpairs"
 include_package_wavefront="wavefront"
@@ -39,6 +40,8 @@ include_package_makeflow="makeflow"
 include_package_ftplite="ftp_lite"
 include_package_s3tools="s3tools"
 include_package_chirp="chirp"
+
+work_queue_bindings=""
 
 if [ -d parrot -a $build_sys = LINUX ]
 then
@@ -65,6 +68,7 @@ rfio_path="/usr"
 dcap_path="/usr"
 irods_path="/usr"
 mysql_path="/usr"
+perl_path="/usr"
 python_path="/usr"
 xrootd_path="/usr"
 mpi_path="/usr/local"
@@ -89,6 +93,7 @@ config_readline_path=auto
 config_globus_path=auto
 config_fuse_path=auto
 config_mysql_path=auto
+config_perl_path=auto
 config_python_path=auto
 config_zlib_path=yes
 
@@ -163,6 +168,11 @@ do
 			shift
 			mysql_path=$1
 			config_mysql_path=yes
+			;;
+		--with-perl-path)
+			shift
+			perl_path=$1
+			config_perl_path=yes
 			;;
 		--with-python-path)
 			shift
@@ -242,6 +252,7 @@ Where PACKAGE may be:
     globus
     irods
     mysql
+    perl
     python
     xrootd
     zlib
@@ -269,7 +280,7 @@ done
 IFS=" "
 export IFS
 
-potential_packages="dttools ${include_package_sand} ${include_package_allpairs} ${include_package_wavefront} ${include_package_makeflow} ${include_package_ftplite} ${include_package_s3tools} ${include_package_chirp} ${include_package_parrot} doc apps"
+potential_packages="dttools ${include_package_work_queue} ${include_package_sand} ${include_package_allpairs} ${include_package_wavefront} ${include_package_makeflow} ${include_package_ftplite} ${include_package_s3tools} ${include_package_chirp} ${include_package_parrot} doc apps"
 
 if [ $build_sys = LINUX ]
 then
@@ -601,6 +612,32 @@ else
 	fi
 fi
 
+if [ $config_perl_path != no ]
+then
+	if check_file ${perl_path}/bin/perl
+	then
+		perl=${perl_path}/bin/perl
+	else
+		perl=0
+	fi
+
+	if [ $perl != 0 ]
+	then
+		perl_ccflags=`perl -MExtUtils::Embed -e ccopts`
+		perl_ldflags=`perl -MExtUtils::Embed -e ldopts`
+		work_queue_bindings="$work_queue_bindings perl"
+	else
+                if [ $config_perl_path = yes ]
+                then
+                        echo "*** Sorry, I couldn't find the perl libraries in $perl_path"
+                        echo "*** Check --with-perl-path and try again."
+                        exit 1
+                else
+                        echo "*** skipping perl support"
+                fi
+	fi
+fi
+
 if [ $config_python_path != no ]
 then
 	if check_file ${python_path}/bin/python2
@@ -617,12 +654,16 @@ then
 	then
 		python_version="$(${python} -V 2>&1)"
 		echo "python version is ${python_version}"
-		if [ `echo ${python_version} | awk '{print $2}' | cut -d . -f 2` -ge 4 ]
+		python_major_version=`echo ${python_version} | awk '{print $2}' | cut -d . -f 2`
+		if [ $python_major_version -ge 4 ]
 		then
-			if check_file ${python_path}/include/python2.[4-7]/Python.h
+			if check_file ${python_path}/include/python2.$python_major_version/Python.h
 			then
 				echo "found python development libraries"
 				packages="${packages} python"
+				python_ccflags=`${python}-config --cflags`
+				python_ldflags=`${python}-config --ldflags`
+				work_queue_bindings="$work_queue_bindings python"
 			else
 				python=0
 			fi
@@ -733,7 +774,15 @@ CCTOOLS_YACC=bison
 CCTOOLS_LEX=flex
 CCTOOLS_DOXYGEN=${doxygen}
 
+CCTOOLS_PERL=${perl}
+CCTOOLS_PERL_CCFLAGS=${perl_ccflags}
+CCTOOLS_PERL_LDFLAGS=${perl_ldflags}
+
 CCTOOLS_PYTHON=${python}
+CCTOOLS_PYTHON_CCFLAGS=${python_ccflags}
+CCTOOLS_PYTHON_LDFLAGS=${python_ldflags}
+
+CCTOOLS_WORK_QUEUE_BINDINGS=${work_queue_bindings}
 EOF
 
 echo ""
