Have configure bail if swig = 1.3.29 and Python is not 2.4.
This resolves bug 921.

#bugfix


git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@2287 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -533,43 +533,6 @@ else
 	fi
 fi
 
-if [ $config_swig_path != no ]
-then
-	swig=""
-	if check_file ${swig_path}/bin/swig
-	then
-		swig=${swig_path}/bin/swig
-	else
-		if check_path swig
-		then
-			swig=`which swig`
-		else
-			echo "*** skipping swig bindings for work queue"
-		fi
-	fi
-
-	if [ -n "$swig" ]
-	then
-		swig_version=`${swig} -version | grep -i version | awk '{print $3}'`
-		if [ `format_version $swig_version` -ge `format_version 1.3.29` ]
-		then
-			packages="${packages} ${include_package_work_queue}"
-		else
-			echo "*** Sorry, I need swig >= 1.3.40"
-			echo "*** skipping swig bindings for work queue"
-		fi
-	fi
-else
-	if [ $config_swig_path = yes ]
-	then
-		echo "*** Sorry, I couldn't find swig in $swig_path"
-		echo "*** Check --with=swig-path and try again."
-		exit 1
-	else
-		echo "*** skipping swig bindings for work queue"
-	fi
-fi
-
 if [ $config_xrootd_path != no ] && check_file ${xrootd_path}/include/xrootd/XrdVersion.hh
 then
 	if [ x$xrootd_arch = xauto ]
@@ -824,6 +787,48 @@ EOF
                 fi
 	fi
 fi
+
+if [ $config_swig_path != no ]
+then
+	swig=""
+	if check_file ${swig_path}/bin/swig
+	then
+		swig=${swig_path}/bin/swig
+	else
+		if check_path swig
+		then
+			swig=`which swig`
+		else
+			echo "*** skipping swig bindings for work queue"
+		fi
+	fi
+
+	if [ -n "$swig" ]
+	then
+		swig_version=`${swig} -version | grep -i version | awk '{print $3}'`
+		if [ "$python" != 1 -a ! \( "$python_major_version" -eq 2 -a "$python_minor_version" -eq 4 \) -a `format_version $swig_version` -eq `format_version 1.3.29` ]
+		then
+			echo "*** Sorry, Swig 1.3.29 does not work with Python $python_version."
+			echo "*** skipping swig bindings for work queue"
+		elif [ `format_version $swig_version` -ge `format_version 1.3.29` ]
+		then
+			packages="${packages} ${include_package_work_queue}"
+		else
+			echo "*** Sorry, I need swig >= 1.3.29"
+			echo "*** skipping swig bindings for work queue"
+		fi
+	fi
+else
+	if [ $config_swig_path = yes ]
+	then
+		echo "*** Sorry, I couldn't find swig in $swig_path"
+		echo "*** Check --with=swig-path and try again."
+		exit 1
+	else
+		echo "*** skipping swig bindings for work queue"
+	fi
+fi
+
 
 linker="gcc"
 
