Regularlized the use of the install program throughout, to avoid differences between linux/bsd/solaris install: - Use the Makefile variable to select the program. - Always give the final argument of install as a directory. - Put space between the -m flag and its argument. - Avoid using /usr/sbin/install on Solaris.
git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/release/3.5.0@2102 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -325,8 +325,26 @@ done
 
 require_path ${ccompiler}
 require_path ${cxxcompiler}
-require_path "install"
 require_gnu_make
+
+require_path install
+install_program=`which install`
+
+if [ $build_sys = SUNOS ]
+then
+	if [ $install_program = /usr/sbin/install ]
+	then
+		echo $install_program is hopelessly broken...
+		install_program=/usr/ucb/install
+		if [ -x $install_program ]
+		then
+			echo "using $install_program instead"
+		else
+			echo "*** Sorry, I can't proceed without $install_program"
+			exit 1
+		fi
+	fi
+fi
 
 #
 # Currently, we rely on the linker --as-needed flag to sort out
@@ -944,6 +962,8 @@ CXXFLAGS=\$(CCTOOLS_CXXFLAGS)
 MPILD=\$(CCTOOLS_MPI_LD)
 
 CCTOOLS_AR=ar
+
+CCTOOLS_INSTALL=${install_program}
 
 CCTOOLS_SWIG=${swig}
 
