standarize golang configuration (e.g. add --with-golang-path)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -94,6 +94,7 @@ curl_path="/usr"
 cvmfs_path="/usr"
 ext2fs_path="/usr"
 fuse_path="/usr"
+golang_path="/usr"
 globus_path="/usr"
 irods_path="/usr"
 mysql_path="/usr"
@@ -122,6 +123,7 @@ config_zlib_path=yes
 
 config_ext2fs_path=auto
 config_fuse_path=auto
+config_golang_path=auto
 config_mysql_path=auto
 config_perl_path=auto
 config_python_path=auto
@@ -216,6 +218,10 @@ do
 			;;
 		--globus-flavor)
 			globus_flavor=${arg}
+			;;
+		--with-golang-path)
+			golang_path=${arg}
+			config_golang_path=$(config_X_path ${arg})
 			;;
 		--with-irods-path)
 			irods_path=${arg}
@@ -1281,71 +1287,40 @@ else
 	echo "umbrella requires python >= 2.6"
 fi
 
-found_swig=no
-if [ $config_swig_path != no ]
+if [ $config_golang_path != no ]
 then
-	if [ "$optstatic" = 1 ]
+	if check_file ${golang_path}/bin/go
 	then
-		echo "*** buildin statically, skipping swig support"
+		golang=${golang_path}/bin/go
 	else
-		swig=""
-		if check_file ${swig_path}/bin/swig
+		golang=0
+	fi
+
+	if [ $golang = 0 ]
+	then
+		if [ $config_golang_path = yes ]
 		then
-			swig=${swig_path}/bin/swig
+			echo "*** Sorry, I couldn't find a go installation in $golang_path"
+			echo "*** Check --with-golang-path and try again."
+			exit 1
 		else
-			if check_path swig
-			then
-				swig=`which swig`
-			else
-				echo "*** skipping swig bindings for work queue"
-			fi
+			echo "*** skipping golang support"
 		fi
-
-		if [ -n "$swig" ]
+	else
+		if [ $found_swig = yes ] && [ "$(${swig} -go --help | grep '\-cgo')" ]
 		then
-			swig_version=`${swig} -version | grep -i version | awk '{print $3}'`
-
-			if [ ! \( "$python_major_version" = 2 -a "$python_minor_version" = 4 \) -a `format_version $swig_version` = `format_version 1.3.29` ]
-			then
-				echo "*** Sorry, Swig 1.3.29 does not work with Python $python_version."
-				echo "*** skipping swig bindings for work queue and chirp"
-			elif [ "$python_dev" = no ]
-			then
-				echo "*** Sorry, Swig needs the develovement files for python (e.g., python-devel, or python-dev)."
-				echo "*** skipping swig bindings for work queue and chirp"
-			elif [ "$python3" != 0 -a `format_version $swig_version` -lt `format_version 2.0.4` ]
-			then
-				# Python 3 requires Swig version >= 2.0.4; cf.
-				# http://sourceforge.net/p/swig/bugs/1104/ and
-				# http://sourceforge.net/p/swig/news/?page=1
-				echo "*** Sorry, Swig $swig_version does not work with Python 3 version $python3_version."
-				echo "*** Specifically, Swig >= 2.0.4 is needed for Python 3 support."
-				echo "*** skipping swig bindings for work queue and chirp"
-				
-			elif [ `format_version $swig_version` -ge `format_version 1.3.29` ]
-			then
-				found_swig=yes
-			else
-				echo "*** Sorry, I need swig >= 1.3.29"
-				echo "*** skipping swig bindings for work queue and chirp"
-			fi
+			swig_bindings="${swig_bindings} golang"
 		else
-			if [ $config_swig_path = yes ]
+			if [ $config_golang_path = yes ]
 			then
-				echo "*** Sorry, I couldn't find swig in $swig_path"
-				echo "*** Check --with=swig-path and try again."
+				echo "*** Sorry, the swig installation does not support golang"
+				echo "*** Check --with-swig-path and try again."
 				exit 1
 			else
-				echo "*** skipping swig bindings for work queue"
+				echo "*** skipping golang support"
 			fi
 		fi
 	fi
-fi
-
-swig_go=no
-if [ "$(${swig} -go --help | grep '\-cgo')" ]
-then
-	swig_go=yes	
 fi
 
 swig_r=no
