Added first pass at xrootd module from Derek Wietzel.
git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@1171 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -60,7 +60,9 @@ irods_path="/usr"
 hdfs_path="/usr"
 mysql_path="/usr"
 python_path="/usr"
+xrootd_path="/usr"
 
+xrootd_arch=auto
 globus_flavor=auto
 has_egee=no
 
@@ -161,6 +163,15 @@ do
 			python_path=$1
 			config_python_path=yes
 			;;
+		--with-xrootd-path)
+			shift
+			xrootd_path=$1
+			config_xrootd_path=yes
+			;;
+		--xrootd-arch)
+		        shift
+			xrootd_arch=1
+			;;
 		--with-*-path)
 			echo "ignoring unknown package $1"
 			shift
@@ -172,6 +183,7 @@ Where options are:
   --help
   --prefix             <path>
   --globus-flavor      <flavor>
+  --xrootd-arch        <arch>
   --with-PACKAGE-path  <path>
 
 Where PACKAGE may be:
@@ -186,6 +198,7 @@ Where PACKAGE may be:
     hdfs
     mysql
     python
+    xrootd
 EOF
 			exit 1
 			;;
@@ -285,6 +298,50 @@ else
 		exit 1
 	else
 		echo "*** skipping dcap support"
+	fi
+fi
+
+if [ $config_xrootd_path != no ] && check_file ${xrootd_path}/include/xrootd/XrdVersion.hh
+then
+	if [ x$xrootd_arch = xauto ]
+	then
+		if [ $build_cpu = X86_64 ] 
+		then
+			xrootd_arch=x86_64_linux_26
+		else
+			xrootd_arch=i386_linux26
+		fi
+	fi
+
+	echo "using an xrootd arch of '$xrootd_arch' (if this is wrong, use the --xrootd-arch argument)"
+
+	if [ ! -d ${xrootd_path}/lib/${xrootd_arch} ]
+	then
+		echo "*** Sorry, couldn't find the xrootd arch directory $xrootd_arch"
+		echo "*** Please set --xrootd-arch to an installed architecture (look in ${xrootd_path}/lib)"
+		exit 1
+	fi
+
+
+	ccflags="${ccflags} -I${xrootd_path}/include/xrootd -DHAS_XROOTD"
+
+	for library in XrdPosix XrdOuc XrdClient XrdSys XrdSec XrdSecgsi Xrd Xrd XrdCrypto XrdSut XrdNet XrdNetUtil XrdCryptossl XrdCryptoLite XrdSecunix XrdSecsss XrdPss XrdBwm
+	do
+		if ! library_search $library ${xrootd_path} ${xrootd_arch}
+		then
+			echo "*** Couldn't find $library in ${xrootd_path}"
+			exit 1
+		fi
+			
+	done
+else
+	if [ $config_xrootd_path = yes ]
+	then
+		echo "*** Sorry, I couldn't find xrootd in ${xrootd_path}"
+		echo "*** Check --with-xrootd-path and try again."
+		exit 1
+	else
+		echo "*** skipping xrootd support"
 	fi
 fi
 
