Revert 1692 for configure
MySQL library requires zlib (for uncompress), so we need to link against it,
even though we don't require it directly.

Perhaps, release wrangler can clean this up.



git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@1706 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -74,6 +74,7 @@ python_path="/usr"
 xrootd_path="/usr"
 cvmfs_path="/usr"
 mpi_path="/usr/local"
+zlib_path="/usr"
 
 xrootd_arch=auto
 globus_flavor=auto
@@ -96,6 +97,7 @@ config_fuse_path=auto
 config_mysql_path=auto
 config_perl_path=auto
 config_python_path=auto
+config_zlib_path=yes
 
 config_krb5_path=no
 config_egee_path=no
@@ -193,6 +195,11 @@ do
 			cvmfs_path=$1
 			config_cvmfs_path=yes
 			;;
+		--with-zlib-path)
+			shift
+			zlib_path=$1
+			config_zlib_path=yes
+			;;
 		--with-mpi-path)
 			shift
 			mpi_path=$1
@@ -260,6 +267,7 @@ Where PACKAGE may be:
     perl
     python
     xrootd
+    zlib
     cvmfs
 
 And SYSTEM may be:
@@ -583,7 +591,7 @@ then
 
 	if [ $build_sys = LINUX ]
 	then
-		cctools_readline_ldflags="-lreadline ${link_no_as_needed} -lncurses -ltermcap -lhistory ${link_as_needed}"
+		cctools_readline_ldflags="-lreadline ${link_no_as_needed} -lncurses -lhistory ${link_as_needed}"
 	else 
 		library_search ncurses ${readline_path}
 		library_search termcap ${readline_path}
@@ -615,6 +623,19 @@ then
         fi
 else
 	echo "*** skipping fuse support"
+fi
+
+if library_search z ${zlib_path}
+then
+	if [ X${zlib_path} != X/usr ]
+	then
+		ccflags="${ccflags} -I${zlib_path}/include"
+		ldflags="${ldflags} -L${zlib_path}/lib"
+	fi
+else
+	echo "*** Sorry, I couldn't find zlib in $zlib_path"
+	echo "*** Check --with-zlib-path and try again."
+	exit 1
 fi
 
 # Solaris places kerberos includes in a strange place.
@@ -782,9 +803,9 @@ fi
 #Hack to get chirp to compile on cygwin.
 if [ ${build_sys} != CYGWIN ]
 then
-	ldflags="${ldflags} -lstdc++ -lpthread -lc -lm"
+	ldflags="${ldflags} -lstdc++ -lpthread -lz -lc -lm"
 else
-	ldflags="${ldflags} -lstdc++ -lpthread -lm"
+	ldflags="${ldflags} -lstdc++ -lpthread -lz -lm"
 fi
 
 
