Adds --with-openssl-path option.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -138,18 +138,18 @@ case "$BUILD_CPU" in
 	;;
 esac
 
-include_package_apps="apps"
-include_package_sand="sand"
 include_package_allpairs="allpairs"
-include_package_wavefront="wavefront"
-include_package_makeflow="makeflow"
-include_package_ftplite="ftp_lite"
+include_package_apps="apps"
 include_package_chirp="chirp"
-include_package_weaver="weaver"
-include_package_umbrella="umbrella"
-include_package_doc="doc"
-include_package_prune="prune"
 include_package_deltadb="deltadb"
+include_package_doc="doc"
+include_package_ftplite="ftp_lite"
+include_package_makeflow="makeflow"
+include_package_prune="prune"
+include_package_sand="sand"
+include_package_umbrella="umbrella"
+include_package_wavefront="wavefront"
+include_package_weaver="weaver"
 
 swig_bindings=""
 
@@ -181,22 +181,23 @@ fi
 
 install_path="$HOME/cctools"
 
-readline_path="/usr"
-globus_path="/usr"
+cvmfs_path="/usr"
 fuse_path="/usr"
+globus_path="/usr"
 irods_path="/usr"
 mysql_path="/usr"
+openssl_path="/usr"
 perl_path="/usr"
 python_path="/usr"
 python3_path="/usr"
-xrootd_path="/usr"
-cvmfs_path="/usr"
-uuid_path="/usr"
-zlib_path="/usr"
+readline_path="/usr"
 swig_path="/usr"
+uuid_path="/usr"
+xrootd_path="/usr"
+zlib_path="/usr"
 
-xrootd_arch=auto
 globus_flavor=auto
+xrootd_arch=auto
 
 ccompiler=gcc
 cxxcompiler=g++
@@ -204,18 +205,21 @@ cxxcompiler=g++
 ccflags="-D__EXTENSIONS__ -D_LARGEFILE64_SOURCE -D__LARGE64_FILES -Wall -Wextra"
 c_only_flags="-std=c99"
 
-config_readline_path=auto
-config_globus_path=auto
+config_zlib_path=yes
+
 config_fuse_path=auto
 config_mysql_path=auto
 config_perl_path=auto
 config_python_path=auto
 config_python3_path=auto
+config_readline_path=auto
+config_swig_path=auto
 
+config_cvmfs_path=no
+config_globus_path=no
+config_openssl_path=no
 config_irods_path=no
 config_xrootd_path=no
-config_cvmfs_path=no
-config_swig_path=auto
 
 while [ $# -gt 0 ]
 do
@@ -259,6 +263,14 @@ do
 				sge_parameters="${sge_parameters}\n\#$ ${arg}"
 			fi
 			;;
+		--with-cvmfs-path)
+			cvmfs_path=${arg}
+			config_cvmfs_path=yes
+			;;
+		--with-fuse-path)
+			fuse_path=${arg}
+			config_fuse_path=yes
+			;;
 		--with-globus-path)
 			globus_path=${arg}
 			if [ "$globus_path" = 'no' ];
@@ -270,24 +282,6 @@ do
 			;;
 		--globus-flavor)
 			globus_flavor=${arg}
-			;;
-		--with-readline-path)
-			readline_path=${arg}
-			if [ "$readline_path" = 'no' ];
-			then
-				config_readline_path=no
-			else
-				config_readline_path=yes
-			fi
-			;;
-		--with-fuse-path)
-			fuse_path=${arg}
-			if [ "$fuse_path" = 'no' ];
-			then
-				config_fuse_path=no
-			else
-				config_fuse_path=yes
-			fi
 			;;
 		--with-irods-path)
 			irods_path=${arg}
@@ -305,6 +299,15 @@ do
 				config_mysql_path=no
 			else
 				config_mysql_path=yes
+			fi
+			;;
+		--with-openssl-path)
+			openssl_path=${arg}
+			if [ "$openssl_path" = 'no' ];
+			then
+				config_openssl_path=no
+			else
+				config_openssl_path=yes
 			fi
 			;;
 		--with-perl-path)
@@ -334,26 +337,20 @@ do
 				config_python3_path=yes
 			fi
 			;;
-		--with-xrootd-path)
-			xrootd_path=${arg}
-			if [ "$xrootd_path" = 'no' ];
-			then
-				config_xrootd_path=no
-			else
-				config_xrootd_path=yes
-			fi
+		--with-readline-path)
+			readline_path=${arg}
+			config_readline_path=yes
 			;;
-		--with-cvmfs-path)
-			cvmfs_path=${arg}
-			if [ "$cvmfs_path" = 'no' ];
-			then
-				config_cvmfs_path=no
-			else
-				config_cvmfs_path=yes
-			fi
+		--with-swig-path)
+			swig_path=${arg}
+			config_swig_path=yes
 			;;
 		--with-uuid-path)
 			uuid_path=${arg}
+			;;
+		--with-xrootd-path)
+			xrootd_path=${arg}
+			config_xrootd_path=yes
 			;;
 		--with-zlib-path)
 			zlib_path=${arg}
@@ -361,15 +358,6 @@ do
 			then
 				echo "*** zlib is not optional"
 				exit 1
-			fi
-			;;
-		--with-swig-path)
-			swig_path=${arg}
-			if [ "$swig_path" = 'no' ];
-			then
-				config_swig_path=no
-			else
-				config_swig_path=yes
 			fi
 			;;
 		--without-system-sand)
@@ -588,8 +576,9 @@ fi
 
 echo "using a globus flavor of '$globus_flavor' (if this is wrong, use the --globus-flavor argument)"
 
-if [ "$config_globus_path" != no ]
+if [ $config_globus_path != no ]
 then
+	config_openssl_path=yes
 	if check_file ${globus_path}/include/${globus_flavor}/globus_common.h
 	then
 		ccflags="${ccflags} -DHAS_GLOBUS_GSS"
@@ -785,6 +774,8 @@ fi
 
 if [ $config_cvmfs_path != no ] && check_file ${cvmfs_path}/include/libcvmfs.h
 then
+	config_openssl_path=yes
+
 	ccflags="${ccflags} -DHAS_CVMFS"
 	cvmfs_ccflags="-I${cvmfs_path}/include"
 
@@ -1222,8 +1213,25 @@ library_search_standard()
 	fi
 }
 
-library_search_standard ssl /usr
-library_search_standard crypto /usr
+
+if [ $config_openssl_path != no ]
+then
+	if ! library_search_standard ssl $openssl_path
+	then
+		echo "*** Couldn't find libssl"
+		echo "*** Check --with-openssl-path and try again."
+		exit 1
+	fi
+
+	if ! library_search_standard crypto $openssl_path
+	then
+		echo "*** Couldn't find libcrypto"
+		echo "*** Check --with-openssl-path and try again."
+		exit 1
+	fi
+fi
+
+# from glibc:
 library_search_standard resolv /usr
 library_search_standard socket /usr
 library_search_standard nsl /usr
@@ -1499,6 +1507,8 @@ CCTOOLS_FUSE_CCFLAGS=${fuse_ccflags}
 
 CCTOOLS_GLOBUS_LDFLAGS=${globus_ldflags}
 CCTOOLS_GLOBUS_CCFLAGS=${globus_ccflags}
+
+export CCTOOLS_TEST_CCFLAGS=${test_ccflags}
 EOF
 
 echo ""
