Explicitly check for libz in configure, issue #462.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -542,21 +542,6 @@ then
 	fi
 
 	ccflags="${ccflags} -DHAS_MYSQL -DHAS_BXGRID"
-
-	# MySQL requires zlib
-	if library_search z ${zlib_path}
-	then
-		if [ X${zlib_path} != X/usr ]
-		then
-		    
-			ccflags="${ccflags} -I${zlib_path}/include"
-			ldflags="${ldflags} -L${zlib_path}/lib"
-		fi
-	else
-		echo "*** Sorry, I couldn't find zlib in $zlib_path"
-		echo "*** Check --with-zlib-path and try again."
-		exit 1
-	fi
 else
 	if [ $config_mysql_path = yes ]
 	then
@@ -1040,14 +1025,26 @@ then
 	external_dynlibs="${external_dynlibs} -ldl"
 fi
 
-#Hack to get chirp to compile on cygwin.
+if library_search z ${zlib_path}
+then
+	if [ X${zlib_path} != X/usr ]
+	then
+		    
+		ccflags="${ccflags} -I${zlib_path}/include"
+		ldflags="${ldflags} -L${zlib_path}/lib"
+	fi
+else
+	echo "*** Sorry, I couldn't find zlib in $zlib_path"
+	echo "*** Check --with-zlib-path and try again."
+	exit 1
+fi
+
 if [ ${build_sys} != CYGWIN ]
 then
 	external_dynlibs="${external_dynlibs} -lstdc++ -lpthread -lz -lc -lm"
 else
 	external_dynlibs="${external_dynlibs} -lstdc++ -lpthread -lz -lm"
 fi
-
 
 if [ $build_sys = DARWIN ]
 then
