Check for libcvmfs > 1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -645,12 +645,16 @@ then
 		exit 1
 	fi
   
-	if library_search uuid "/usr"
+	cvmfs_version=$(sed -En 's/^#define LIBCVMFS_VERSION +([0-9]+)/\1/p' ${cvmfs_path}/include/libcvmfs.h)
+	if [ $cvmfs_version -gt 1 ]
 	then
-		cvmfs_ldflags="${cvmfs_ldflags} ${library_search_result}"
-	else
-		echo "*** Couldn't find libuuid"
-		exit 1
+		if library_search uuid "/usr"
+		then
+			cvmfs_ldflags="${cvmfs_ldflags} ${library_search_result}"
+		else
+			echo "*** Couldn't find libuuid"
+			exit 1
+		fi
 	fi
 else
 	if [ $config_cvmfs_path = yes ]
