Reworked the configuration for linking. Library search now has four options: require_static, prefer_static, prefer_dynamic, and require_dynamic. Most standard system libraries are now linked dynamically and selectively, with a number of unneeded dependencies removed. Most unpackaged third-party systems are still linked statically. Systems which no longer see much use, like krb5, are no longer built by default.
git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@1133 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -49,30 +49,15 @@ fi
 
 install_path="$HOME/cctools"
 
-grep Fedora /etc/issue > /dev/null 2>&1
-if [ $? -eq 0 ]
-then
-	globus_path="/usr"
-else
-	globus_path="/usr/local"
-fi
-
 krb5_path="/usr"
 readline_path="/usr"
-
-if [ ${build_sys} = DARWIN -o ${build_sys} = FREEBSD ]
-then
-	fuse_path="/usr/local"
-else
-	fuse_path="/usr"
-fi
-
+globus_path="/usr"
+fuse_path="/usr"
 egee_path="/opt"
 rfio_path="/usr"
 dcap_path="/usr"
 irods_path="/usr"
 hdfs_path="/usr"
-zlib_path="/usr"
 mysql_path="/usr"
 python_path="/usr"
 
@@ -90,16 +75,17 @@ fi
 
 config_readline_path=auto
 config_globus_path=auto
-config_krb5_path=auto
 config_fuse_path=auto
+config_mysql_path=auto
+config_python_path=auto
+
+config_krb5_path=no
 config_egee_path=no
 config_rfio_path=no
 config_dcap_path=no
 config_irods_path=no
 config_hdfs_path=no
-config_zlib_path=yes
-config_mysql_path=no
-config_python_path=auto
+
 
 if [ "X${GLOBUS_LOCATION}" != "X" ]
 then
@@ -165,11 +151,6 @@ do
 			hdfs_path=$1
 			config_hdfs_path=yes
 			;;
-		--with-zlib-path)
-			shift
-			zlib_path=$1
-			config_zlib_path=yes
-			;;
 		--with-mysql-path)
 			shift
 			mysql_path=$1
@@ -197,14 +178,12 @@ Where PACKAGE may be:
     readline
     egee
     krb5
-    gdb
     fuse
     rfio
     dcap
     globus
     irods
     hdfs
-    zlib
     mysql
     python
 EOF
@@ -223,7 +202,7 @@ export IFS
 
 if [ $build_sys = LINUX ]
 then
-	ldflags="-Xlinker -Bstatic -Xlinker --as-needed -lstdc++ -static-libgcc -Xlinker -Bdynamic"
+	ldflags="-Xlinker -Bstatic -Xlinker -lstdc++ -static-libgcc -Xlinker -Bdynamic -Xlinker --as-needed "
 else
 	ldflags="-lstdc++ -static-libgcc"
 fi
@@ -250,6 +229,12 @@ require_path ${ccompiler}
 require_path ${cxxcompiler}
 require_path "install"
 require_gnu_make
+
+##########################################################################
+# SWITCH TO STATIC LINKING FOR UNCOMMON THIRD-PARTY PACKAGES
+##########################################################################
+library_search_mode=prefer_static
+##########################################################################
 
 if [ $config_egee_path != no ] && check_file "${egee_path}/lcg/include/lcg_util.h"
 then
@@ -327,38 +312,16 @@ else
 			ldflags="${ldflags} -L${globus_path}/lib"
 			for library in globus_gss_assist globus_gssapi_gsi globus_gsi_proxy_core globus_gsi_credential globus_gsi_callback globus_oldgaa globus_gsi_sysconfig globus_gsi_cert_utils globus_openssl globus_openssl_error globus_callout globus_proxy_ssl globus_common ltdl
 			do
-				libpath="${globus_path}/lib/lib${library}_${globus_flavor}.a"
-				require_file $libpath
-				ldflags="${ldflags} $libpath"
+				library_search ${library}_${globus_flavor} ${globus_path}
 			done
-
-			library_search ssl /usr
-			library_search crypto /usr
-			library_search gssapi_krb5 /usr
-			config_krb5_path=yes
-
 		elif check_file ${globus_path}/include/globus/globus_common.h
 		then
-			# Notes about Globus on Fedora...
-			#  o libraries are in /usr/lib/
-			#  o headers are in /usr/include/globus/
-			#  o there is no flavor
-			#  o there are no static libraries
-			#  o globus_config.h is in /usr/lib/globus/include
 			ccflags="${ccflags} -I${globus_path}/lib/globus/include -I${globus_path}/include/globus -DHAS_GLOBUS_GSS"
 			ldflags="${ldflags} -L${globus_path}/lib"
 			for library in globus_gss_assist globus_gssapi_gsi globus_gsi_proxy_core globus_gsi_credential globus_gsi_callback globus_oldgaa globus_gsi_sysconfig globus_gsi_cert_utils globus_openssl globus_openssl_error globus_callout globus_proxy_ssl globus_common ltdl
 			do
-				libpath="${globus_path}/lib/lib${library}.so"
-				require_file $libpath
-				ldflags="${ldflags} -l${library}"
+				library_search $library ${globus_path}
 			done
-
-			library_search ssl /usr
-			library_search crypto /usr
-			library_search gssapi_krb5 /usr
-			config_krb5_path=yes
-
 		else
 			if [ $config_globus_path = yes ]
 			then
@@ -461,21 +424,6 @@ else
 	fi
 fi
 
-if [ $config_readline_path != no ] && library_search readline ${readline_path}
-then
-	if [ ${readline_path} != /usr ]
-	then
-		ccflags="${ccflags} -I${readline_path}/include"
-	fi
-	
-	ccflags="${ccflags} -DHAS_LIBREADLINE"
-
-	library_search ncurses ${readline_path}
-	library_search history ${readline_path}
-else
-	echo "*** skipping readline..."
-fi
-
 if [ $config_mysql_path != no ] && library_search mysqlclient ${mysql_path} mysql
 then
 	if [ ${mysql_path} != /usr ]
@@ -484,13 +432,6 @@ then
 	fi
 
 	ccflags="${ccflags} -DHAS_MYSQL -DHAS_BXGRID"
-
-	library_search mystrings ${mysql_path} mysql
-	library_search mysys ${mysql_path} mysql
-	library_search ssl /usr
-	library_search crypto /usr
-
-	config_krb5_path=yes
 else
 	if [ $config_mysql_path = yes ]
 	then
@@ -502,37 +443,35 @@ else
 	fi
 fi
 
-# Solaris places kerberos includes in a strange place.
+##########################################################################
+# SWITCH BACK TO DYNAMIC LINKING FOR COMMON SYSTEM LIBRARIES
+##########################################################################
+library_search_mode=prefer_dynamic
+##########################################################################
 
-if [ -d ${krb5_path}/include/kerberosv5 ]
+if [ $config_readline_path != no ] && library_search readline ${readline_path}
 then
-	krb5_include_path=${krb5_path}/include/kerberosv5
-else
-	krb5_include_path=${krb5_path}/include
-fi
-
-if [ $config_krb5_path != no ] && check_file ${krb5_include_path}/krb5.h && library_search krb5 "${krb5_path}"
-then
-	if [ ${krb5_include_path} != /usr/include ]
+	if [ ${readline_path} != /usr ]
 	then
-		ccflags="${ccflags} -I${krb5_include_path}"
+		ccflags="${ccflags} -I${readline_path}/include"
 	fi
-
-	ccflags="${ccflags} -DHAS_KRB5"
 	
-	library_search k5crypto    "${krb5_path}"
-	library_search crypto      "${krb5_path}"
-	library_search com_err     "${krb5_path}"
-	library_search krb5support "${krb5_path}"
-else
-	if [ $config_krb5_path = yes ]
+	ccflags="${ccflags} -DHAS_LIBREADLINE"
+
+	# We rely on the --as-needed flag to figure out what dynamic
+	# libraries are actually used by each executable.
+	# However, libreadline doesn't properly specify a dependency
+	# on ncurses and history, so we must force them to link.
+
+	if [ $build_sys = LINUX ]
 	then
-		echo "*** Sorry, I couldn't find Kerberos in $krb5_path"
-		echo "*** Check --with-krb5-path and try again."
-		exit 1
+		cctools_readline_ldflags="-Xlinker --no-as-needed -lncurses -lhistory -Xlinker --as-needed"
 	else
-		echo "*** skipping krb5 support"
+		library_search ncurses ${readline_path}
+		library_search history ${readline_path}
 	fi
+else
+	echo "*** skipping readline..."
 fi
 
 if [ $config_fuse_path != no ]
@@ -559,17 +498,32 @@ else
 	echo "*** skipping fuse support"
 fi
 
-if [ $config_zlib_path != no ] && library_search z ${zlib_path}
+# Solaris places kerberos includes in a strange place.
+
+if [ -d ${krb5_path}/include/kerberosv5 ]
 then
-	if [ ${zlib_path} != /usr ]
-	then	
-        	ccflags="${ccflags} -I${zlib_path}/include"
+	krb5_include_path=${krb5_path}/include/kerberosv5
+else
+	krb5_include_path=${krb5_path}/include
+fi
+
+if [ $config_krb5_path != no ] && check_file ${krb5_include_path}/krb5.h && library_search krb5 "${krb5_path}"
+then
+	if [ ${krb5_include_path} != /usr/include ]
+	then
+		ccflags="${ccflags} -I${krb5_include_path}"
 	fi
 
-	ccflags="${ccflags} -DHAS_ZLIB"
+	ccflags="${ccflags} -DHAS_KRB5"
 else
-	echo "*** Sorry, you must have zlib to build this package."
-	exit 1
+	if [ $config_krb5_path = yes ]
+	then
+		echo "*** Sorry, I couldn't find Kerberos in $krb5_path"
+		echo "*** Check --with-krb5-path and try again."
+		exit 1
+	else
+		echo "*** skipping krb5 support"
+	fi
 fi
 
 if [ $config_python_path != no ]
@@ -604,6 +558,23 @@ then
     fi
 fi
 
+linker="gcc"
+
+library_search ssl	/usr
+library_search crypto	/usr
+library_search resolv   /usr
+library_search socket   /usr
+library_search nsl      /usr
+
+# Finally, add in standard system libraries found everywhere
+
+if [ $build_sys != DARWIN ]
+then
+	ldflags="${ldflags} -lrt"
+fi
+
+ldflags="${ldflags} -ldl -lpthread -lz -lc -lm"
+
 optional_function strsignal /usr/include/string.h HAS_STRSIGNAL
 optional_function pread /usr/include/unistd.h HAS_PREAD
 optional_function pwrite /usr/include/unistd.h HAS_PWRITE
@@ -611,26 +582,6 @@ optional_function pwrite /usr/include/unistd.h HAS_PWRITE
 optional_file /usr/include/sys/statfs.h HAS_SYS_STATFS_H
 optional_file /usr/include/sys/statvfs.h HAS_SYS_STATVFS_H
 optional_file /usr/include/alloca.h HAS_ALLOCA_H
-
-linker="gcc"
-
-library_search crypto   /usr
-library_search selinux  /usr
-library_search sepol    /usr
-library_search keyutils-1.2 /
-library_search resolv   /usr
-library_search socket   /usr
-library_search nsl      /usr
-library_search iconv    /usr
-
-# Finally, add in standard system libraries that are better off being dynamically linked.
-
-if [ $build_sys != DARWIN ]
-then
-	ldflags="${ldflags} -lrt"
-fi
-
-ldflags="${ldflags} -ldl -lpthread -lm -lc"
 
 if check_path doxygen
 then
@@ -663,6 +614,8 @@ CCTOOLS_LD=@echo LINK \$@; ${linker}
 CCTOOLS_BASE_LDFLAGS=${ldflags}
 CCTOOLS_INTERNAL_LDFLAGS= ${internal_ldflags} \${CCTOOLS_BASE_LDFLAGS}
 CCTOOLS_LDFLAGS=-L\${CCTOOLS_INSTALL_DIR}/lib \${CCTOOLS_BASE_LDFLAGS}
+
+CCTOOLS_READLINE_LDFLAGS=${cctools_readline_ldflags}
 
 CC=\$(CCTOOLS_CC)
 CCFLAGS=\$(CCTOOLS_CCFLAGS)
