configure: fix globus detection on Fedora
Patches from Matthew Farrellee.


git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@418 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -48,7 +48,13 @@ else
 fi
 
 install_path="/usr/local"
-globus_path="/usr/local"
+grep Fedora /etc/issue > /dev/null 2>&1
+if [ $? -eq 0 ]
+then
+	globus_path="/usr"
+else
+	globus_path="/usr/local"
+fi
 krb5_path="/usr"
 gcb_path="/usr/local"
 readline_path="/usr"
@@ -79,7 +85,7 @@ then
 fi
 
 config_readline_path=auto
-config_globus_path=no
+config_globus_path=auto
 config_krb5_path=auto
 config_gcb_path=no
 config_fuse_path=auto
@@ -313,7 +319,7 @@ if [ $has_egee = yes ]
 then	
 	echo "using egee version of globus"
 else
-	if [ $globus_flavor = auto ]
+	if [ x$globus_flavor = xauto ]
 	then
 		if [ $build_cpu = X86_64 ] 
 		then
@@ -323,18 +329,46 @@ else
 		fi
 	fi
 
-	echo "using a globus flavor of $globus_flavor (if this is wrong, use the --globus-flavor argument)"
+	echo "using a globus flavor of '$globus_flavor' (if this is wrong, use the --globus-flavor argument)"
 
-	if [ $config_globus_path != no ] && check_file ${globus_path}/include/${globus_flavor}/globus_common.h
+	if [ $config_globus_path != no ]
 	then
-		ccflags="${ccflags} -I${globus_path}/include/${globus_flavor} -DHAS_GLOBUS_GSS"
-		ldflags="${ldflags} -L${globus_path}/lib"
-		for library in globus_gss_assist globus_gssapi_gsi globus_gsi_proxy_core globus_gsi_credential globus_gsi_callback globus_oldgaa globus_gsi_sysconfig globus_gsi_cert_utils globus_openssl globus_openssl_error globus_callout globus_proxy_ssl globus_common ltdl
-		do
-			libpath="${globus_path}/lib/lib${library}_${globus_flavor}.a"
-			require_file $libpath
-			ldflags="${ldflags} $libpath"
-		done
+		if check_file ${globus_path}/include/${globus_flavor}/globus_common.h
+		then
+			ccflags="${ccflags} -I${globus_path}/include/${globus_flavor} -DHAS_GLOBUS_GSS"
+			ldflags="${ldflags} -L${globus_path}/lib"
+			for library in globus_gss_assist globus_gssapi_gsi globus_gsi_proxy_core globus_gsi_credential globus_gsi_callback globus_oldgaa globus_gsi_sysconfig globus_gsi_cert_utils globus_openssl globus_openssl_error globus_callout globus_proxy_ssl globus_common ltdl
+			do
+				libpath="${globus_path}/lib/lib${library}_${globus_flavor}.a"
+				require_file $libpath
+				ldflags="${ldflags} $libpath"
+			done
+		elif check_file ${globus_path}/include/globus/globus_common.h
+		then
+			# Notes about Globus on Fedora...
+			#  o libraries are in /usr/lib/
+			#  o headers are in /usr/include/globus/
+			#  o there is no flavor
+			#  o there are no static libraries
+			#  o globus_config.h is in /usr/lib/globus/include
+			ccflags="${ccflags} -I${globus_path}/lib/globus/include -I${globus_path}/include/globus -DHAS_GLOBUS_GSS"
+			ldflags="${ldflags} -L${globus_path}/lib"
+			for library in globus_gss_assist globus_gssapi_gsi globus_gsi_proxy_core globus_gsi_credential globus_gsi_callback globus_oldgaa globus_gsi_sysconfig globus_gsi_cert_utils globus_openssl globus_openssl_error globus_callout globus_proxy_ssl globus_common ltdl
+			do
+				libpath="${globus_path}/lib/lib${library}.so"
+				require_file $libpath
+				ldflags="${ldflags} -l${library}"
+			done
+		else
+			if [ $config_globus_path = yes ]
+			then
+				echo "*** Sorry, I couldn't find Globus in $globus_path"
+				echo "*** Check --with-globus-path and try again."
+				exit 1
+			else
+				echo "*** skipping globus support"
+			fi
+		fi
 
 		library_search ssl /usr
 		library_search crypto /usr
@@ -343,14 +377,7 @@ else
 		# globus depends upon kerberos
 		config_krb5_path=yes
 	else
-		if [ $config_globus_path = yes ]
-		then
-			echo "*** Sorry, I couldn't find Globus in $globus_path"
-			echo "*** Check --with-globus-path and try again."
-			exit 1
-		else
-			echo "*** skipping globus support"
-		fi
+		echo "*** skipping globus support"
 	fi
 fi
 
