Changed configure script to generate a template shell script to use in starting parrot/chirp when using HDFS. The script also now sets HADOOP_HOME and JAVA_HOME if the user has not by using the values at the time of configure.
git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@700 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -401,6 +401,56 @@ then
 		exit 1
 	fi
 
+	# Make a HDFS Environment Setup Script Template
+	# Automatically sets JAVA_HOME and HADOOP_HOME for the user if absent.
+	HDFS_TEMPLATE='#!/bin/sh
+
+if [ -z "$JAVA_HOME" ]; then
+  JAVA_HOME="'"$JAVA_HOME"'"
+fi
+export JAVA_HOME
+
+if [ -z "$HADOOP_HOME" ]; then
+  HADOOP_HOME="'"$hdfs_path"'"
+fi
+export HADOOP_HOME
+
+if [ -z $CLASSPATH ]; then
+  CLASSPATH=${JAVA_HOME}/jdk/jre/lib
+else
+  CLASSPATH=${CLASSPATH}:${JAVA_HOME}/jdk/jre/lib
+fi
+CLASSPATH=${CLASSPATH}:$(ls ${HADOOP_HOME}/hadoop-*-core.jar | head -n 1)
+CLASSPATH=${CLASSPATH}:${HADOOP_HOME}/conf
+for f in ${HADOOP_HOME}/lib/*.jar; do
+  CLASSPATH=${CLASSPATH}:$f
+done
+export CLASSPATH
+
+if [ -z $LIBJVM_PATH ]; then
+  LIBJVM_PATH=$(find $JAVA_HOME -follow -name libjvm.so | head -1l)
+  if [ -z $LIBJVM_PATH ]; then
+    echo 2>&1 "Sorry but could not find libjvm.so anywhere under JAVA_HOME"
+    exit 1
+  fi
+fi
+export LIBJVM_PATH
+
+if [ -z $LIBHDFS_PATH ]; then
+  if [ $(uname -m) = x86_64 ]; then
+    LIBHDFS_PATH="$HADOOP_HOME/c++/$(uname)-amd64-64/lib/libhdfs.so"
+  else
+    LIBHDFS_PATH="$HADOOP_HOME/c++/$(uname)-i386-32/lib/libhdfs.so"
+  fi
+  if [ ! -e $LIBHDFS_PATH ]; then
+    echo 2>&1 "Sorry but could not find libhdfs.so anywhere under HADOOP_HOME"
+    exit 1
+  fi
+fi
+export LIBHDFS_PATH
+
+'
+	echo -n "$HDFS_TEMPLATE" > hdfs-setup.template
 	ccflags="${ccflags} -I ${hdfs_path}/src/c++/libhdfs -DHAS_HDFS"
 	ccflags="${ccflags} -I ${JAVA_HOME}/include -I ${JAVA_HOME}/include/$(echo $build_sys | tr \[A-Z\] \[a-z\])"
 else
