Fixed up configure to test for presence of Python include files, in addition to the binary.
git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@1330 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -604,34 +604,46 @@ fi
 
 if [ $config_python_path != no ]
 then
-    if check_file ${python_path}/bin/python2
-    then
-	python=${python_path}/bin/python2
-    elif check_file ${python_path}/bin/python
-    then
-	python=${python_path}/bin/python
-    else
-    	python=0
-	if [ $config_python_path = yes ]
-	then
-	    echo "*** Sorry, I couldn't find Python in $python_path"
-	    echo "*** Check --with-python-path and try again."
-	    exit 1
+	if check_file ${python_path}/bin/python2
+	then	
+		python=${python_path}/bin/python2
+	elif check_file ${python_path}/bin/python
+ 	then
+		python=${python_path}/bin/python
 	else
-	    echo "*** skipping python support"
+		python=0
 	fi
-    fi
 
-    if [ $python != 0 ]
-    then
-	python_version="$(${python} -V 2>&1)"
-	if [ `echo ${python_version} | awk '{print $2}' | cut -d . -f 2` -lt 6 ]
+	if [ $python != 0 ]
 	then
-	    echo "*** Sorry, you have ${python_version}, we require Python >= 2.6.x"
-	else
-	    packages="${packages} python"
+		python_version="$(${python} -V 2>&1)"
+		echo "python version is ${python_version}"
+		if [ `echo ${python_version} | awk '{print $2}' | cut -d . -f 2` -ge 6 ]
+		then
+			if check_file ${python_path}/include/python2.6/Python.h
+			then
+				echo "found python development libraries"
+				packages="${packages} python"
+			else
+				python=0
+			fi
+		else
+			echo "*** Sorry, we require Python >= 2.6.0"
+			python=0
+		fi
 	fi
-    fi
+
+	if [ $python = 0 ]
+	then
+                if [ $config_python_path = yes ]
+                then
+                        echo "*** Sorry, I couldn't find the Python > 2.6.0 libraries in $python_path"
+                        echo "*** Check --with-python-path and try again."
+                        exit 1
+                else
+                        echo "*** skipping python support"
+                fi
+	fi
 fi
 
 linker="gcc"
