svn merge file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@1316 file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@1435 .
git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/branches/pdonnel3/search-syscall@1436 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,8 +7,8 @@ uname -a
 save_arguments $0 $@
 
 major=3
-minor=3
-micro=3
+minor=4
+micro=0
 
 build_user=`whoami`
 build_host=`uname -n`
@@ -70,6 +70,7 @@ mysql_path="/usr"
 python_path="/usr"
 xrootd_path="/usr"
 mpi_path="/usr/local"
+zlib_path="/usr"
 
 xrootd_arch=auto
 globus_flavor=auto
@@ -90,8 +91,8 @@ config_readline_path=auto
 config_globus_path=auto
 config_fuse_path=auto
 config_mysql_path=auto
-config_mpi_path=auto
 config_python_path=auto
+config_zlib_path=yes
 
 config_krb5_path=no
 config_egee_path=no
@@ -99,6 +100,7 @@ config_rfio_path=no
 config_dcap_path=no
 config_irods_path=no
 config_xrootd_path=no
+config_mpi_path=no
 
 if [ "X${GLOBUS_LOCATION}" != "X" ]
 then
@@ -174,6 +176,11 @@ do
 			xrootd_path=$1
 			config_xrootd_path=yes
 			;;
+		--with-zlib-path)
+			shift
+			zlib_path=$1
+			config_zlib_path=yes
+			;;
 		--with-mpi-path)
 			shift
 			mpi_path=$1
@@ -239,7 +246,7 @@ Where PACKAGE may be:
     mysql
     python
     xrootd
-    mpi
+    zlib
 
 And SYSTEM may be:
     sand
@@ -268,10 +275,12 @@ potential_packages="dttools ${include_package_sand} ${include_package_allpairs} 
 
 if [ $build_sys = LINUX ]
 then
-	ldflags="-Xlinker -Bstatic -Xlinker -lstdc++ -static-libgcc -Xlinker -Bdynamic -Xlinker --as-needed "
+	ldflags="-Xlinker -Bstatic -static-libgcc -Xlinker -Bdynamic -Xlinker --as-needed "
 else
-	ldflags="-lstdc++ -static-libgcc"
+	ldflags="-static-libgcc"
 fi
+
+check_multiarch
 
 rm -f Makefile.config
 echo "checking for all the things I know how to build..."
@@ -459,12 +468,6 @@ else
     fi
 fi
 
-##########################################################################
-# SWITCH BACK TO DYNAMIC LINKING FOR COMMON SYSTEM LIBRARIES
-##########################################################################
-library_search_mode=prefer_dynamic
-##########################################################################
-
 if [ $config_xrootd_path != no ] && check_file ${xrootd_path}/include/xrootd/XrdVersion.hh
 then
 	if [ x$xrootd_arch = xauto ]
@@ -481,7 +484,7 @@ then
 
 	ccflags="${ccflags} -I${xrootd_path}/include/xrootd -DHAS_XROOTD"
 
-	for library in XrdPosix XrdOuc XrdClient XrdSys XrdSec XrdSecgsi Xrd Xrd XrdCrypto XrdSut XrdNet XrdNetUtil XrdCryptossl XrdCryptoLite XrdSecunix XrdSecsss XrdPss XrdBwm
+	for library in XrdPosix XrdClient XrdSys XrdNet XrdNetUtil XrdOuc
 	do
 		if ! library_search $library ${xrootd_path} ${xrootd_arch}
 		then
@@ -500,6 +503,12 @@ else
 		echo "*** skipping xrootd support"
 	fi
 fi
+
+##########################################################################
+# SWITCH BACK TO DYNAMIC LINKING FOR COMMON SYSTEM LIBRARIES
+##########################################################################
+library_search_mode=prefer_dynamic
+##########################################################################
 
 if [ $config_readline_path != no ] && library_search readline ${readline_path}
 then
@@ -551,6 +560,19 @@ else
 	echo "*** skipping fuse support"
 fi
 
+if library_search z ${zlib_path}
+then
+	if [ X${zlib_path} != X/usr ]
+	then
+		ccflags="${ccflags} -I${zlib_path}/include"
+		ldflags="${ldflags} -L${zlib_path}/lib"
+	fi
+else
+	echo "*** Sorry, I couldn't find zlib in $zlib_path"
+	echo "*** Check --with-zlib-path and try again."
+	exit 1
+fi
+
 # Solaris places kerberos includes in a strange place.
 
 if [ -d ${krb5_path}/include/kerberosv5 ]
@@ -583,34 +605,46 @@ fi
 
 if [ $config_python_path != no ]
 then
-    if check_file ${python_path}/bin/python2
-    then
-	python=${python_path}/bin/python2
-    elif check_file ${python_path}/bin/python
-    then
-	python=${python_path}/bin/python
-    else
-    	python=0
-	if [ $config_python_path = yes ]
-	then
-	    echo "*** Sorry, I couldn't find Python in $python_path"
-	    echo "*** Check --with-python-path and try again."
-	    exit 1
+	if check_file ${python_path}/bin/python2
+	then	
+		python=${python_path}/bin/python2
+	elif check_file ${python_path}/bin/python
+ 	then
+		python=${python_path}/bin/python
 	else
-	    echo "*** skipping python support"
+		python=0
 	fi
-    fi
 
-    if [ $python != 0 ]
-    then
-	python_version="$(${python} -V 2>&1)"
-	if [ `echo ${python_version} | awk '{print $2}' | cut -d . -f 2` -lt 6 ]
+	if [ $python != 0 ]
 	then
-	    echo "*** Sorry, you have ${python_version}, we require Python >= 2.6.x"
-	else
-	    packages="${packages} python"
+		python_version="$(${python} -V 2>&1)"
+		echo "python version is ${python_version}"
+		if [ `echo ${python_version} | awk '{print $2}' | cut -d . -f 2` -ge 6 ]
+		then
+			if check_file ${python_path}/include/python2.[6-7]/Python.h
+			then
+				echo "found python development libraries"
+				packages="${packages} python"
+			else
+				python=0
+			fi
+		else
+			echo "*** Sorry, we require Python >= 2.6.0"
+			python=0
+		fi
 	fi
-    fi
+
+	if [ $python = 0 ]
+	then
+                if [ $config_python_path = yes ]
+                then
+                        echo "*** Sorry, I couldn't find the Python > 2.6.0 libraries in $python_path"
+                        echo "*** Check --with-python-path and try again."
+                        exit 1
+                else
+                        echo "*** skipping python support"
+                fi
+	fi
 fi
 
 linker="gcc"
@@ -628,7 +662,7 @@ then
 	ldflags="${ldflags} -lrt"
 fi
 
-ldflags="${ldflags} -ldl -lpthread -lz -lc -lm"
+ldflags="${ldflags} -lstdc++ -ldl -lpthread -lz -lc -lm"
 
 if [ $build_sys = DARWIN ]
 then
@@ -643,9 +677,9 @@ optional_function strsignal /usr/include/string.h HAS_STRSIGNAL
 optional_function pread /usr/include/unistd.h HAS_PREAD
 optional_function pwrite /usr/include/unistd.h HAS_PWRITE
 
-optional_file /usr/include/sys/statfs.h HAS_SYS_STATFS_H
-optional_file /usr/include/sys/statvfs.h HAS_SYS_STATVFS_H
-optional_file /usr/include/alloca.h HAS_ALLOCA_H
+optional_include /usr/include/sys/statfs.h HAS_SYS_STATFS_H
+optional_include /usr/include/sys/statvfs.h HAS_SYS_STATVFS_H
+optional_include /usr/include/alloca.h HAS_ALLOCA_H
 
 if check_path doxygen
 then
