Moved xrootd into the dynamic linking section. Added flag for xrootd in supported filesystem list.
git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@1173 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -87,7 +87,7 @@ config_rfio_path=no
 config_dcap_path=no
 config_irods_path=no
 config_hdfs_path=no
-
+config_xrootd_path=no
 
 if [ "X${GLOBUS_LOCATION}" != "X" ]
 then
@@ -301,50 +301,6 @@ else
 	fi
 fi
 
-if [ $config_xrootd_path != no ] && check_file ${xrootd_path}/include/xrootd/XrdVersion.hh
-then
-	if [ x$xrootd_arch = xauto ]
-	then
-		if [ $build_cpu = X86_64 ] 
-		then
-			xrootd_arch=x86_64_linux_26
-		else
-			xrootd_arch=i386_linux26
-		fi
-	fi
-
-	echo "using an xrootd arch of '$xrootd_arch' (if this is wrong, use the --xrootd-arch argument)"
-
-	if [ ! -d ${xrootd_path}/lib/${xrootd_arch} ]
-	then
-		echo "*** Sorry, couldn't find the xrootd arch directory $xrootd_arch"
-		echo "*** Please set --xrootd-arch to an installed architecture (look in ${xrootd_path}/lib)"
-		exit 1
-	fi
-
-
-	ccflags="${ccflags} -I${xrootd_path}/include/xrootd -DHAS_XROOTD"
-
-	for library in XrdPosix XrdOuc XrdClient XrdSys XrdSec XrdSecgsi Xrd Xrd XrdCrypto XrdSut XrdNet XrdNetUtil XrdCryptossl XrdCryptoLite XrdSecunix XrdSecsss XrdPss XrdBwm
-	do
-		if ! library_search $library ${xrootd_path} ${xrootd_arch}
-		then
-			echo "*** Couldn't find $library in ${xrootd_path}"
-			exit 1
-		fi
-			
-	done
-else
-	if [ $config_xrootd_path = yes ]
-	then
-		echo "*** Sorry, I couldn't find xrootd in ${xrootd_path}"
-		echo "*** Check --with-xrootd-path and try again."
-		exit 1
-	else
-		echo "*** skipping xrootd support"
-	fi
-fi
-
 if [ $has_egee = yes ]
 then	
 	echo "using egee version of globus"
@@ -511,6 +467,50 @@ fi
 ##########################################################################
 library_search_mode=prefer_dynamic
 ##########################################################################
+
+if [ $config_xrootd_path != no ] && check_file ${xrootd_path}/include/xrootd/XrdVersion.hh
+then
+	if [ x$xrootd_arch = xauto ]
+	then
+		if [ $build_cpu = X86_64 ] 
+		then
+			xrootd_arch=x86_64_linux_26
+		else
+			xrootd_arch=i386_linux26
+		fi
+	fi
+
+	echo "using an xrootd arch of '$xrootd_arch' (if this is wrong, use the --xrootd-arch argument)"
+
+	if [ ! -d ${xrootd_path}/lib/${xrootd_arch} ]
+	then
+		echo "*** Sorry, couldn't find the xrootd arch directory $xrootd_arch"
+		echo "*** Please set --xrootd-arch to an installed architecture (look in ${xrootd_path}/lib)"
+		exit 1
+	fi
+
+
+	ccflags="${ccflags} -I${xrootd_path}/include/xrootd -DHAS_XROOTD"
+
+	for library in XrdPosix XrdOuc XrdClient XrdSys XrdSec XrdSecgsi Xrd Xrd XrdCrypto XrdSut XrdNet XrdNetUtil XrdCryptossl XrdCryptoLite XrdSecunix XrdSecsss XrdPss XrdBwm
+	do
+		if ! library_search $library ${xrootd_path} ${xrootd_arch}
+		then
+			echo "*** Couldn't find $library in ${xrootd_path}"
+			exit 1
+		fi
+			
+	done
+else
+	if [ $config_xrootd_path = yes ]
+	then
+		echo "*** Sorry, I couldn't find xrootd in ${xrootd_path}"
+		echo "*** Check --with-xrootd-path and try again."
+		exit 1
+	else
+		echo "*** skipping xrootd support"
+	fi
+fi
 
 if [ $config_readline_path != no ] && library_search readline ${readline_path}
 then
