cleaner python configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -109,7 +109,8 @@ config_fuse_path=auto
 config_golang_path=auto
 config_mysql_path=auto
 config_perl_path=auto
-config_python_path=auto
+config_python_path=auto    # for python2 or python3, version automatically detected
+config_python2_path=auto
 config_python3_path=auto
 config_readline_path=auto
 config_swig_path=auto
@@ -233,6 +234,10 @@ do
 		--with-python-path)
 			python_path=${arg}
 			config_python_path=$(config_X_path ${arg})
+			;;
+		--with-python2-path)
+			python2_path=${arg}
+			config_python2_path=$(config_X_path ${arg})
 			;;
 		--with-python3-path)
 			python3_path=${arg}
@@ -977,196 +982,193 @@ fi
 report_detection perl "${perl_avail}" "${config_perl_path}" "${perl_path}"
 
 
-python=0    #to be set to the python path
+### This section does not configure python, only determines which version to
+### use (2 or 3) when not specified.
 if [ $config_python_path != no ]
 then
 	python_path=${python_path:-${base_root}}
-	if [ -n "$PYTHON" ] && check_file ${PYTHON}
+	python_exe=""
+
+	if [ "${config_python_path}" = auto ] && search_file_executable python python3 python2 > /dev/null 2>&1
 	then
-		python=${PYTHON}
-	elif check_file ${python_path}/bin/python2
+		python_exe=${executable_search_result}
+	elif search_file_executable ${python_path}{,/python,/python3,/python2} > /dev/null 2>&1
 	then
-		python=${python_path}/bin/python2
-	elif check_file ${python_path}/bin/python
-	then
-		python=${python_path}/bin/python
-	else
-		python=0
+		python_exe=${executable_search_result}
 	fi
 
-if [ $python != 0 ]
-then
-	python_version=`${python} -V 2>&1 | cut -d " " -f 2`
-	echo "python version is ${python_version}"
-	python_major_version=`echo ${python_version} | cut -d . -f 1`
-	python_minor_version=`echo ${python_version} | cut -d . -f 2 | cut -d . -f 1,2`
-	if [ "$python_major_version" = 2 -a "$python_minor_version" -ge 4 ]
+	if [ -n "${python_exe}" ]
 	then
-		if check_file ${python_path}/include/python2.$python_minor_version/Python.h
+		python_major_version=$(${python_exe} -c 'import sys; print(sys.version_info[0])' 2> /dev/null)
+
+		# only set python*_path if not already explicitely set
+		if [ "${config_python2_path}" != yes -a "${config_python3_path}" = auto -a "${python_major_version}" = 3 ]
 		then
-			echo "found python development libraries"
-			python_ccflags_file=`mktemp tmp.XXXXXX`
-			python_ldflags_file=`mktemp tmp.XXXXXX`
-			python_dev=yes
+			python3_path=${python_path}
+			config_python2_path=no
+		elif [ "${config_python2_path}" = auto -a "${config_python3_path}" != yes -a "${python_major_version}" = 2 ]
+		then
+			python2_path=${python_path}
+			config_python3_path=no
+		fi
+	fi
+fi
 
-			env HOME=/var/empty ${python} > $python_ccflags_file <<EOF
-from distutils import sysconfig
-flags = ['-I' + sysconfig.get_python_inc(),
-	 '-I' + sysconfig.get_python_inc(plat_specific=True)]
-syscfgflags = sysconfig.get_config_var('CFLAGS')
-if not syscfgflags is None:
-	flags.extend(syscfgflags.split())
-print ' '.join(flags)
-EOF
-			env HOME=/var/empty ${python} > $python_ldflags_file <<EOF
-from distutils import sysconfig
-libs = sysconfig.get_config_var('LIBS').split() + sysconfig.get_config_var('SYSLIBS').split()
-if not sysconfig.get_config_var('Py_ENABLE_SHARED'):
-	libs.insert(0, '-L' + sysconfig.get_config_var('LIBPL'))
-print ' '.join(libs)
-EOF
+### configure python2
+python2_avail=no
+python2_exe=""
+python2_version=""
+if [ $config_python2_path != no ]
+then
+	python2_avail=yes
+	python2_path=${python_path:-${base_root}}
 
-			python_ccflags=`cat $python_ccflags_file`
-			python_ldflags=`cat $python_ldflags_file`
-			rm $python_ccflags_file
-			rm $python_ldflags_file
+	if [ "${swig_avail}" = no ]
+	then
+		echo "*** swig is needed for python2 support"
+		python2_avail=no
+	elif [ $(format_version ${swig_version}) -lt $(format_version 1.3.29) ]
+	then
+		echo "*** swig version ${swig_version} is older than 1.3.29, disabling python2 support"
+		python2_avail=no
+	elif [ "${config_python2_path}" = auto ] && search_file_executable python python2
+	then
+		python2_exe=${executable_search_result}
+	elif search_file_executable ${python2_path}{,/bin/python,/bin/python2,/python,/python2}
+	then
+		python2_exe=${executable_search_result}
+	else
+		python2_avail=no
+	fi
 
-# On OSX, the ExtUtils::Embed options contain options
-# to generate triple-fat binaries, which fails when
-# we attempt to bring in our thin binaries.
+	if [ "${python2_avail}" = yes ]
+	then
+		python2_version=$(${python2_exe} -c 'import sys; print("{}.{}".format(sys.version_info[0],sys.version_info[1]))' 2> /dev/null)
 
-# To avoid this problem, remove all of the -arch XXX
-# arguments, so that the compiler produces the default,
-# which will be compatible with the other objects we compile.
+		if [ -z "${python2_version}" ]
+		then
+			echo "*** could not find version of python from ${python2_exe}"
+			python2_avail=no
+		elif [ $(format_version ${python2_version}) -lt $(format_version 2.4) ]
+		then
+			echo "*** python ${python2_version} is too old"
+			python2_avail=no
+		elif [ $(format_version ${python2_version}) -ge $(format_version 3.0) ]
+		then
+			echo "*** ${python2_exe} version ${python2_version} is not a python2"
+			python2_avail=no
+		fi
+	fi
 
-			if [ ${BUILD_SYS} = DARWIN ]
-			then
-				python_ccflags=`echo ${python_ccflags} | sed 's/-arch [^ ]* *//g'`
-				python_ldflags=`echo ${python_ldflags} | sed 's/-arch [^ ]* *//g'`
-			fi
+	if [ "${python2_avail}" = yes ]
+	then
+		if check_file ${python2_exe}${python2_version}-config
+		then
+			python2_ccflags=$(${python2_exe}${python2_version}-config --includes)
+			python2_ldflags=$(${python2_exe}${python2_version}-config --ldflags)
 
 			if [ $BUILD_SYS = DARWIN ]
 			then
-				python_ldflags="$python_ldflags -undefined dynamic_lookup"
+				python2_ldflags="$python2_ldflags -undefined dynamic_lookup"
 			fi
 
-			swig_bindings="$swig_bindings python"
+			if ! check_function Py_MATH_PI Python.h ${python2_ccflags} ${python2_ldflags}
+			then
+				echo "*** could not find python2 development files"
+				python2_avail=no
+			fi
 		else
-			python_dev=no
+			echo "*** could not find ${python2_exe}${python2_version}-config"
+			python2_avail=no
 		fi
-	else
-		echo "*** Sorry, we require Python >= 2.4"
-		python=0
 	fi
-fi
-fi
 
-if [ "$python_dev" = no ]
-then
-	if [ $config_python_path = yes ]
+	if [ "${python2_avail}" = yes ]
 	then
-		echo "*** Sorry, I couldn't find the Python >= 2.4 libraries in $python_path"
-		echo "*** Check --with-python-path and try again."
-		exit 1
-	else
-		echo "*** skipping python bindings support"
+		# to change to python2
+		swig_bindings="$swig_bindings python"
 	fi
 fi
 
+report_detection python2 "${python2_avail}" "${config_python2_path}" "${python2_path}"
+
+
+### configure python3
+python3_avail=no
+python3_exe=""
+python3_version=""
 if [ $config_python3_path != no ]
 then
-	python3_path=${python3_path:-${base_root}}
-	if [ -n "$PYTHON3" ] && check_file ${PYTHON3}
+	python3_avail=yes
+	python3_path=${python_path:-${base_root}}
+
+	if [ "${swig_avail}" = no ]
 	then
-		python3=${PYTHON3}
-	elif check_file ${python3_path}/bin/python3
+		echo "*** swig is needed for python3 support"
+		python3_avail=no
+	elif [ $(format_version ${swig_version}) -lt $(format_version 2.0.4) ]
 	then
-		python3=${python3_path}/bin/python3
-	elif check_file ${python3_path}/bin/python
+		echo "*** swig version ${swig_version} is older than 2.0.4, disabling python3 support"
+		python3_avail=no
+	elif [ "${config_python3_path}" = auto ] && search_file_executable python python3
 	then
-		python3=${python3_path}/bin/python
+		python3_exe=${executable_search_result}
+	elif search_file_executable ${python3_path}{,/bin/python,/bin/python3,/python,/python3}
+	then
+		python3_exe=${executable_search_result}
 	else
-		python3=0
+		python3_avail=no
 	fi
 
-	if check_file ${python3_path}/bin/2to3
+	if [ "${python3_avail}" = yes ]
 	then
-		python3_2to3=${python3_path}/bin/2to3
-	else
-		python3=0
-	fi
-	if [ $python3 != 0 ]
-	then
-		python3_version=`${python3} -V 2>&1 | cut -d " " -f 2`
-		echo "python3 version is ${python3_version}"
-		python3_major_version=`echo ${python3_version} | cut -d . -f 1`
-		python3_minor_version=`echo ${python3_version} | cut -d . -f 2 | cut -d . -f 1,2`
-		if [ "$python3_major_version" = 3 ]
+		python3_version=$(${python3_exe} -c 'import sys; print("{}.{}".format(sys.version_info[0],sys.version_info[1]))' 2> /dev/null)
+
+		if [ -z "${python3_version}" ]
 		then
-			python3_include=`${python3} -c 'from distutils import sysconfig; print(sysconfig.get_python_inc())'`
-			if check_file ${python3_include}/Python.h && check_file ${python3}-config
+			echo "*** could not find version of python from ${python3_exe}"
+			python3_avail=no
+		elif [ $(format_version ${python3_version}) -lt $(format_version 3.0) ]
+		then
+			echo "*** ${python3_exe} version ${python3_version} is not a python3"
+			python3_avail=no
+		fi
+	fi
+
+	if [ "${python3_avail}" = yes ]
+	then
+		if check_file ${python3_exe}${python3_version}-config
+		then
+			python3_ccflags=$(${python3_exe}${python3_version}-config --includes)
+			python3_ldflags=$(${python3_exe}${python3_version}-config --ldflags)
+
+			if [ $BUILD_SYS = DARWIN ]
 			then
-				echo "found python3 development libraries"
-				python3_ccflags=$(${python3}-config --includes)
-				# python3_ldflags=$(${python3}-config --ldflags) # it includes static libs, so we need:
-				python3_ldflags_file=`mktemp tmp.XXXXXX`
-				env HOME=/var/empty ${python3} > $python3_ldflags_file <<EOF
-from distutils import sysconfig
-flags = ['-I' + sysconfig.get_python_inc(), '-I' + sysconfig.get_python_inc(plat_specific=True)]
-syscfgflags = sysconfig.get_config_var('CFLAGS')
-if not syscfgflags is None:
-    flags.extend(syscfgflags.split())
-print(' '.join(flags))
-EOF
-				python3_ldflags=$(cat $python3_ldflags_file)
-				rm $python3_ldflags_file
+				python3_ldflags="$python3_ldflags -undefined dynamic_lookup"
+			fi
 
-				# On OSX, the ExtUtils::Embed options contain options
-				# to generate triple-fat binaries, which fails when
-				# we attempt to bring in our thin binaries.
-
-				# To avoid this problem, remove all of the -arch XXX
-				# arguments, so that the compiler produces the default,
-				# which will be compatible with the other objects we compile.
-
-				if [ ${BUILD_SYS} = DARWIN ]
-				then
-					python3_ccflags=`echo ${python3_ccflags} | sed 's/-arch [^ ]* *//g'`
-					python3_ldflags=`echo ${python3_ldflags} | sed 's/-arch [^ ]* *//g'`
-				fi
-
-				if [ $BUILD_SYS = DARWIN ]
-				then
-					python3_ldflags="$python3_ldflags -undefined dynamic_lookup"
-				fi
-
-				if [ ${found_swig} = old ]
-				then
-					echo "*** Sorry, for Python3 swig 2.0.4 is required."
-				else
-					swig_bindings="$swig_bindings python3"
-				fi
-			else
-				python3=0
+			if ! check_function Py_MATH_PI Python.h ${python3_ccflags} ${python3_ldflags}
+			then
+				echo "*** could not find python3 development files"
+				python3_avail=no
 			fi
 		else
-			echo "*** Sorry, we require Python3 >= 3.0"
-			python3=0
+			echo "*** could not find ${python3_exe}${python3_version}-config"
+			python3_avail=no
 		fi
 	fi
 
-	if [ $python3 = 0 ]
+	if [ "${python3_avail}" = yes ]
 	then
-		if [ $config_python3_path = yes ]
-		then
-			echo "*** Sorry, I couldn't find the Python3 >= 3.0 libraries in $python3_path"
-			echo "*** Check --with-python3-path and try again."
-			exit 1
-		else
-			echo "*** skipping python3 support"
-		fi
+		swig_bindings="$swig_bindings python3 python"
+
+		# 2to3 need soon to be removed, so we don't check much for it right now.
+		python3_2to3=$(dirname ${python3_exe})/bin/2to3
 	fi
 fi
+
+report_detection python3 "${python3_avail}" "${config_python3_path}" "${python3_path}"
+
 
 
 if [ "$fuse_avail" != yes ]; then
@@ -1636,16 +1638,18 @@ CCTOOLS_PYTHON_LDFLAGS=\$(CCTOOLS_PYTHON2_LDFLAGS)
 CCTOOLS_PYTHON_VERSION=\$(CCTOOLS_PYTHON2_VERSION)
 CCTOOLS_PYTHON_PATH=\$(CCTOOLS_INSTALL_DIR)/lib/python\$(CCTOOLS_PYTHON_VERSION)/site-packages
 
-CCTOOLS_PYTHON2=${python}
-CCTOOLS_PYTHON2_CCFLAGS=${python_ccflags}
-CCTOOLS_PYTHON2_LDFLAGS=${python_ldflags}
-CCTOOLS_PYTHON2_VERSION=${python_major_version}.${python_minor_version}
+CCTOOLS_PYTHON2_AVAILABLE=${python2_avail}
+CCTOOLS_PYTHON2=${python2_exe}
+CCTOOLS_PYTHON2_CCFLAGS=${python2_ccflags}
+CCTOOLS_PYTHON2_LDFLAGS=${python2_ldflags}
+CCTOOLS_PYTHON2_VERSION=${python2_version}
 CCTOOLS_PYTHON2_PATH=\$(CCTOOLS_INSTALL_DIR)/lib/python\$(CCTOOLS_PYTHON2_VERSION)/site-packages
 
-CCTOOLS_PYTHON3=${python3}
+CCTOOLS_PYTHON3_AVAILABLE=${python3_avail}
+CCTOOLS_PYTHON3=${python3_exe}
 CCTOOLS_PYTHON3_CCFLAGS=-DNDEBUG ${python3_ccflags}
 CCTOOLS_PYTHON3_LDFLAGS=${python3_ldflags}
-CCTOOLS_PYTHON3_VERSION=${python3_major_version}.${python3_minor_version}
+CCTOOLS_PYTHON3_VERSION=${python3_version}
 CCTOOLS_PYTHON3_2TO3=${python3_2to3}
 CCTOOLS_PYTHON3_PATH=\$(CCTOOLS_INSTALL_DIR)/lib/python\$(CCTOOLS_PYTHON3_VERSION)/site-packages
 
