Change configure to --with-mpi-path for consistency with other options.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -97,6 +97,7 @@ fuse_path="/usr"
 golang_path="/usr"
 globus_path="/usr"
 irods_path="/usr"
+mpi_path="/usr"
 mysql_path="/usr"
 openssl_path="/usr"
 perl_path="/usr"
@@ -135,7 +136,7 @@ config_curl_path=no
 config_cvmfs_path=no
 config_globus_path=no
 config_irods_path=no
-config_mpicc_path=auto
+config_mpi_path=no
 config_openssl_path=no
 config_xrootd_path=no
 
@@ -230,9 +231,9 @@ do
 		--irods-flavor)
 			irods_flavor=${arg}
 			;;
-		--with-mpicc-path)
-			mpicc_path=${arg}
-			config_mpicc_path=$(config_X_path ${arg})
+		--with-mpi-path)
+			mpi_path=${arg}
+			config_mpi_path=$(config_X_path ${arg})
 			;;
 		--with-mysql-path)
 			mysql_path=${arg}
@@ -366,7 +367,7 @@ Where PACKAGE may be:
 	fuse
 	globus
 	irods
-	mpicc
+	mpi
 	mysql
 	perl
 	python
@@ -827,33 +828,31 @@ else
 	echo "*** skipping ext2fs support"
 fi
 
-echon "checking for mpicc..."
-if [ "$config_mpicc_path" != no ]
+if [ "$config_mpi_path" != no ]
 then
-	if [ $config_mpicc_path = auto ]
+	if check_file "$mpi_path/bin/mpicc"
 	then
-		if which mpicc 2> /dev/null
-		then
-			mpicc_path=$(which mpicc)
-		else
-			echo "*** skipping mipcc support"
-		fi
-	else
-		if [ -x "$mpicc_path/bin/mpicc" ]
-		then
-			mpicc="$mpicc_path/bin/mpicc"
-			ccflags="-DCCTOOLS_WITH_MPI ${ccflags}"
-			ccompiler=${mpicc}
-			linker=${mpicc}
-			echo "mpicc: $mpicc"
-		else 
-			echo "*** Sorry, I couldn't find mpicc in $mpicc_path"
-			echo "*** Check --with-mpicc-path and try again."
-			exit 1
-		fi
+		mpicc="$mpi_path/bin/mpicc"
+	elif check_file "$mpi_path/mpicc"
+	then
+		mpicc="$mpi_path/mpicc"
+	elif check_file "$mpi_path"
+	then
+		mpicc="$mpi_path"
+	fi
+
+	if [ X$mpicc != X ]
+	then
+		ccflags="-DCCTOOLS_WITH_MPI ${ccflags}"
+		ccompiler=${mpicc}
+		linker=${mpicc}
+	else 
+		echo "*** Sorry, I couldn't find mpicc in $mpi_path"
+		echo "*** Check --with-mpicc-path and try again."
+		exit 1
 	fi
 else
-	echo "no"
+	echo "*** skipping mpi support"
 fi
 
 ##########################################################################
