Add -t <time> option to {condor,sge}_submit_workers
git-svn-id: file:///afs/nd.edu/user37/ccl/svn/cctools/trunk@516 a4d8336d-3463-0410-8bba-c098c45d37a8

diff --git a/dttools/src/condor_submit_workers b/dttools/src/condor_submit_workers
--- a/dttools/src/condor_submit_workers
+++ b/dttools/src/condor_submit_workers
@@ -1,9 +1,30 @@
 #!/bin/sh
 
+show_help() 
+{
+	echo "Use: condor_submit_workers [options] <servername> <port> <num-workers>"
+	echo "options:"
+	echo "  -t <time> Abort after this amount of idle time. (default=900s)"
+	echo "  -h        Show this help message."
+	exit 1
+}
+
+timeout=900
+
+while getopts ht: opt 
+do
+	case "$opt" in
+		t)  timeout=$OPTARG ;;
+		h)  show_help;;
+		\?) show_help;;
+	esac
+done
+
+shift $(expr $OPTIND - 1)
+
 if [ X$3 = X ]
 then
-	echo "use: condor_submit_workers <servername> <port> <num-workers>"
-	exit 1
+	show_help	
 fi
 
 worker=`which worker`
@@ -24,7 +45,7 @@ count=$3
 condor_submit << EOF
 universe = vanilla
 executable = worker
-arguments = $host $port
+arguments = -t $timeout $host $port
 transfer_input_files = worker
 should_transfer_files = yes
 when_to_transfer_output = on_exit
diff --git a/dttools/src/sge_submit_workers b/dttools/src/sge_submit_workers
--- a/dttools/src/sge_submit_workers
+++ b/dttools/src/sge_submit_workers
@@ -1,9 +1,30 @@
 #!/bin/sh
 
+show_help() 
+{
+	echo "Use: sge_submit_workers [options] <servername> <port> <num-workers>"
+	echo "options:"
+	echo "  -t <time> Abort after this amount of idle time. (default=900s)"
+	echo "  -h        Show this help message."
+	exit 1
+}
+
+timeout=900
+
+while getopts ht: opt 
+do
+	case "$opt" in
+		t)  timeout=$OPTARG ;;
+		h)  show_help;;
+		\?) show_help;;
+	esac
+done
+
+shift $(expr $OPTIND - 1)
+
 if [ X$3 = X ]
 then
-	echo "use: sge_submit_workers <servername> <port> <num-workers>"
-	exit 1
+	show_help	
 fi
 
 worker=`which worker 2>/dev/null`
@@ -30,7 +51,7 @@ cp $worker .
 
 cat >worker.sh <<EOF
 #!/bin/sh
-./worker $host $port
+./worker -t $timeout $host $port
 EOF
 
 chmod 755 worker.sh
