Updated submit scripts to process password option correctly.

diff --git a/dttools/src/condor_submit_workers b/dttools/src/condor_submit_workers
--- a/dttools/src/condor_submit_workers
+++ b/dttools/src/condor_submit_workers
@@ -18,6 +18,7 @@ show_help()
 	echo "  -O <os>             Set operating system string for the worker to report to master instead of the value in uname."
 	echo "  -s <path>           Set the location for creating the working directory of the worker."
 	echo "  -r <requirements>   Condor requirements ClassAd."
+	echo "  -P <pwfile>         Password file to authenticate workers to master."
 	echo "  -h                  Show this help message."
 	exit 1
 }
@@ -28,10 +29,13 @@ show_help()
 
 requirements="(Memory>0)"
 
+submit_dir=/tmp/${USER}-workers
 arguments=""
 use_auto=0
+transfer_input_files="work_queue_worker"
+pwfile=""
 
-while getopts aM:N:C:t:d:w:i:b:z:A:O:s:r:h opt 
+while getopts aM:N:C:t:d:w:i:b:z:A:O:s:r:P:h opt 
 do
 	case "$opt" in
 		a)  arguments="$arguments -a"; use_auto=1;;
@@ -48,6 +52,8 @@ do
 		O)  arguments="$arguments -O $OPTARG";;
 		s)  arguments="$arguments -s $OPTARG";;
 		r)  requirements="$requirments $OPTARG";;
+	        P)  pwfile=$OPTARG
+		    arguments="$arguments -P $pwfile";;
 		h)  show_help;;
 		\?) show_help;;
 	esac
@@ -73,6 +79,33 @@ else
     count=$1
 fi
 
+# Set up a local temporary directory to manage the log files.
+# home directories on shared filesystems are often not accessible
+# to Condor, so this saves some headaches for the user.
+
+echo "Creating worker submit scripts in ${submit_dir}..."
+
+mkdir -p ${submit_dir}
+
+# If a password file has been selected, check for existence,
+# copy it into the submission directory, then add it to
+# the transfer input files list.
+
+if [ X${pwfile} != X ]
+then
+	if [ ! -f $pwfile ]
+	then
+		echo "condor_submit_workers: password file $pwfile not found"
+		exit 1
+	fi
+
+	cp $pwfile ${submit_dir}
+	transfer_input_files="${transfer_input_files}, $pwfile"
+fi
+
+# Copy the worker executable into the temporary directory,
+# for similar reasons.
+
 worker=`which work_queue_worker 2>/dev/null`
 if [ $? != 0 ]
 then
@@ -80,15 +113,14 @@ then
 	exit 1
 fi
 
-[ -d /tmp/$USER-workers ] || mkdir /tmp/${USER}-workers
-cd /tmp/${USER}-workers
+cd ${submit_dir}
 cp $worker .
 
 condor_submit << EOF
 universe = vanilla
 executable = work_queue_worker
 arguments = $arguments $host $port
-transfer_input_files = work_queue_worker
+transfer_input_files = ${transfer_input_files}
 should_transfer_files = yes
 when_to_transfer_output = on_exit
 output = worker.\$(PROCESS).output
