Add options in makeflow_graph_log to support specifying paths for gnuplot and convert (#2864)
* Add options to support specifying paths to gnuplot and convert

diff --git a/makeflow/src/makeflow_graph_log b/makeflow/src/makeflow_graph_log
--- a/makeflow/src/makeflow_graph_log
+++ b/makeflow/src/makeflow_graph_log
@@ -10,16 +10,30 @@
 
 show_help()
 {
-	echo "use: makeflow_graph_log <makeflowlog> <imagefile>"
+	echo "use: makeflow_graph_log [options] <makeflowlog> <imagefile>"
+	echo "	-g <gnuplot-path> Specify the location of the gnuplot executable."
+	echo "			  Default is gnuplot."
+	echo "	-c <convert-path> Specify the location of the convert executable."
+	echo "			  Default is convert."
 	exit 1
 }
 
+gnuplot='gnuplot'
+convert='convert'
 while [ $# -gt 0 ]
 do
 	case $1 in
 	-h |--help )
 		show_help
 		exit 1
+		;;
+	-g)
+		shift
+		gnuplot="$1"
+		;;
+	-c)
+		shift
+		convert="$1"
 		;;
 	*)
 		break
@@ -36,23 +50,21 @@ fi
 
 infile=$1
 outfile=$2
-tempfile=$outfile.tmp
+tempfile="${outfile}.tmp"
 output_format=${outfile##*.}
 
 # check for the necessary programs in the path
 
 for prog in gnuplot convert
 do
-   if which $prog >& /dev/null
+   if ! which ${prog} >& /dev/null
    then
-	  true
-   else
-	  echo "$0: could not find $prog in your PATH"
+	  echo "$0: could not find $prog in the PATH variable or in the specified path"
 	  exit 1
    fi
 done
 
-if [ ! -f $infile ]
+if [ ! -f "$infile" ]
 then
 	echo "$0: $infile does not exist"
 	exit 1
@@ -63,9 +75,9 @@ fi
 # to always generate a precise and attractive EPS, and then
 # rely upon convert to yield the appropriate output format.
 
-gnuplot <<EOF
+"${gnuplot}" <<EOF
 set terminal postscript solid eps 24 color
-set output "$tempfile"
+set output "${tempfile}"
 set size 2,1
 set timefmt "%s"
 set xdata time
@@ -74,13 +86,13 @@ set y2label "Jobs Running"
 set y2tics
 set style line 1
 set key top left
-plot "$infile" using (\$1/1000000):(\$6+\$7+\$8+\$9) title "Submitted" with lines lw 5, "" using (\$1/1000000):6 title "Running" with lines lw 5, "" using (\$1/1000000):7 title "Complete" with lines lw 5
+plot "${infile}" using (\$1/1000000):(\$6+\$7+\$8+\$9) title "Submitted" with lines lw 5, "" using (\$1/1000000):6 title "Running" with lines lw 5, "" using (\$1/1000000):7 title "Complete" with lines lw 5
 EOF
 
 if [ $output_format = "eps" ]
 then
-	mv $tempfile $outfile
+	mv "${tempfile}" "${outfile}"
 else
-	convert eps:$tempfile -background white -flatten -antialias $outfile
-	rm $tempfile
+	"${convert}" eps:"${tempfile}" -background white -flatten -antialias "${outfile}"
+	rm "${tempfile}"
 fi
