Submit workers extras (#4111)
* vine: add --extra-input-file to submit script

* add support for custom wrappers to submit script

diff --git a/taskvine/src/tools/vine_submit_workers b/taskvine/src/tools/vine_submit_workers
--- a/taskvine/src/tools/vine_submit_workers
+++ b/taskvine/src/tools/vine_submit_workers
@@ -6,6 +6,8 @@ submit_dir=
 use_manager_name=0
 pwfile=""
 arguments=""
+wrapper=
+input_files=
 
 poncho_env=""
 
@@ -25,7 +27,7 @@ condor_docker_universe=
 condor_class_ads=
 condor_requirements=
 condor_parameters=
-condor_transfer_input_files="vine_worker, cctools_gpu_autodetect"
+condor_transfer_input_files=
 
 uge_use_jobarray=0
 uge_parameters=""
@@ -45,6 +47,7 @@ condor_show_help()
     echo "  --autosize                Condor will automatically size the worker to the slot."
     echo "  --spool                   Spool required input files."
     echo "  --docker-universe <image> Run worker inside <image> using condor's docker universe."
+	echo "  --extra-file <path>       Extra file to ship with worker job."
     echo "  -p <parameters>           HTCondor condor_submit parameters."
     echo ""
 }
@@ -97,6 +100,7 @@ show_help()
 	echo "  --disk <size>             Manually set the amount of disk (in MB) reported by this worker."
 	echo "  --scratch-dir             Set the scratch directory location created on the local machine (default=/tmp/USER-workers)." 
 	echo "  -E,--worker-options <str> Extra options passed to vine_worker."
+    echo "  --wrapper <str>           Command line to prepend to worker cxommand."
 	echo "  --poncho-env <file.tar.gz>  Run each worker inside this poncho environment."
 	echo "  -h,--help                 Show this help message."
 	echo ""
@@ -187,24 +191,26 @@ condor_parse_arguments()
     return "$consumed"
 }
 
-condor_set_up_password_file()
-{
-    condor_transfer_input_files="${condor_transfer_input_files}, $pwfile"
-}
-
 condor_submit_workers_command()
 {
     condor_setup
+    condor_transfer_input_files=${condor_transfer_input_files}
+
+    worker_command="./vine_worker"
+    if [ -n "$wrapper" ]
+    then
+        worker_command="$wrapper $worker_command"
+    fi
 
     if [ -n "$poncho_env" ]; then
-        condor_transfer_input_files="${condor_transfer_input_files}, poncho_package_run, $poncho_env"
-
-        executable="poncho_package_run"
-        arguments="-e $poncho_env -- ./vine_worker $arguments $host $port"
-    else
-        executable="vine_worker"
-        arguments="$arguments $host $port"
+        worker_command="./poncho_package_run -e $poncho_env -- ${worker_command}"
     fi
+
+    cat > worker.sh <<EOF
+#!/bin/sh
+${worker_command} "\$@"
+EOF
+    chmod 755 worker.sh
 
     if [ -n "${condor_docker_universe}" ]
     then
@@ -219,9 +225,9 @@ EOF
     fi
 
     cat >> condor_submit_file <<EOF
-executable = $executable
-arguments = $arguments
-transfer_input_files = ${condor_transfer_input_files}
+executable = worker.sh
+arguments = ${arguments} ${host} ${port}
+transfer_input_files = worker.sh,${condor_transfer_input_files}
 should_transfer_files = yes
 when_to_transfer_output = on_exit
 output = worker.\$(CLUSTER).\$(PROCESS).output
@@ -253,6 +259,10 @@ EOF
 
     if [ "${dry_run}" = 1 ]
     then
+        condor_submit_cmd="echo worker command"
+        echo "######## worker.sh ########"
+        cat worker.sh
+        echo "####################################"
         condor_submit_cmd="echo condor_submit"
         echo "######## condor_submit_file ########"
         cat condor_submit_file
@@ -295,12 +305,22 @@ slurm_parse_arguments()
 slurm_submit_workers_command()
 {
     slurm_setup
+    worker_command="${submit_dir}/vine_worker $arguments $host $port"
+    if [ -n "$wrapper" ]
+    then
+        worker_command="$wrapper $worker_command"
+    fi
 
     if [ -n "$poncho_env" ]; then
-        worker_command="${submit_dir}/poncho_package_run -e ${submit_dir}/$(basename "$poncho_env") -- ${submit_dir}/vine_worker $arguments $host $port"
-    else
-        worker_command="${submit_dir}/vine_worker $arguments $host $port"
+        worker_command="${submit_dir}/poncho_package_run -e ${submit_dir}/$poncho_env -- ${worker_command}"
     fi
+
+    cat > ${submit_dir}/worker.sh <<EOF
+#!/bin/sh
+${worker_command}
+EOF
+
+    chmod 755 ${submit_dir}/worker.sh
 
     if [ "${dry_run}" = 0 ]
     then
@@ -313,8 +333,7 @@ slurm_submit_workers_command()
     else
         sbatch="echo sbatch"
         echo "######## worker.sh ########"
-        echo "#!/bin/sh"
-        echo "${worker_command}"
+        cat ${submit_dir}/worker.sh
         echo "####################################"
     fi
 
@@ -322,10 +341,7 @@ slurm_submit_workers_command()
     while [ "$to_submit" -gt 0 ]
     do
         to_submit=$((to_submit-1))
-        ${sbatch} --job-name vineWorker --ntasks=1 --nodes=1 $slurm_parameters <<EOF
-#!/bin/sh
-${worker_command}
-EOF
+        ${sbatch} --job-name vineWorker --ntasks=1 --nodes=1 $slurm_parameters ${submit_dir}/worker.sh
     done
 
 }
@@ -370,16 +386,18 @@ uge_parse_arguments()
 uge_submit_workers_command()
 {
     uge_setup
+    worker_command="${submit_dir}/vine_worker $arguments $host $port"
+    if [ -n "$wrapper" ]
+    then
+        worker_command="$wrapper $worker_command"
+    fi
 
     if [ -n "$poncho_env" ]; then
-        worker_command="${submit_dir}/poncho_package_run -e ${submit_dir}/$(basename "$poncho_env") -- ${submit_dir}/vine_worker $arguments $host $port"
-    else
-        worker_command="${submit_dir}/vine_worker $arguments $host $port"
+        worker_command="${submit_dir}/poncho_package_run -e ${submit_dir}/$poncho_env -- ${worker_command}"
     fi
 
     cat >worker.sh <<EOF
 #!/bin/sh
-
 ${worker_command}
 EOF
 
@@ -414,6 +432,19 @@ EOF
     fi
 }
 
+add_input_file()
+{
+    base=$(basename $1)
+
+    if [ -z "${input_files}" ]
+    then
+        input_files="$1"
+    else
+        input_files="${input_files} $1"
+    fi
+}
+
+
 
 parse_arguments_general()
 {
@@ -431,7 +462,7 @@ parse_arguments_general()
                 condor)
                     parse_arguments_batch=condor_parse_arguments
                 ;;
-                uge)
+                uge|sge)
                     parse_arguments_batch=uge_parse_arguments
                 ;;
                 slurm)
@@ -442,6 +473,11 @@ parse_arguments_general()
                     exit 1
                 ;;
             esac
+            consumed=2
+        ;;
+        --extra-file)
+            shift
+            add_input_file $1
             consumed=2
         ;;
         --dry-run)
@@ -614,9 +650,13 @@ parse_arguments_worker()
             shift
             arguments="$arguments $1"
         ;;
-        --poncho-env)
+        --poncho-env|--python-env)
             shift
             poncho_env="$1"
+        ;;
+        --wrapper)
+            shift
+            wrapper="$1"
         ;;
         -h | --help)
             show_help 0
@@ -694,6 +734,8 @@ set_up_working_directory()
 	then
 		echo "$0: please add 'vine_worker' to your PATH." 1>&2
 		exit 1
+    else
+        add_input_file $worker
 	fi
 
     gpu_detection=$(which cctools_gpu_autodetect 2>/dev/null)
@@ -701,7 +743,7 @@ set_up_working_directory()
 	then
 		echo "$0: could not find cctools_gpu_autodetect in PATH. gpus will not be automatically detected." 1>&2
 	else
-		cp "$gpu_detection" "${submit_dir}"
+        add_input_file $gpu_detection
 	fi
 
 	if [ -n "$poncho_env" ]; then
@@ -712,12 +754,15 @@ set_up_working_directory()
 			exit 1
 		fi
 
-		cp "$poncho_bin" "${submit_dir}"
-		cp "$poncho_env" "${submit_dir}"
+        add_input_file $poncho_bin
+        add_input_file $poncho_env
+
+        poncho_bin=$(basename ${poncho_bin})
+        poncho_env=$(basename ${poncho_env})
 	fi
 
-    cp "${worker}" "${submit_dir}"
 	set_up_password_file
+    set_up_input_files
 
 	cd "${submit_dir}" || exit 1
 }
@@ -735,14 +780,25 @@ set_up_password_file()
 			echo "$script_name password file $pwfile not found" 1>&2
 			exit 1
 		fi
+        add_input_file ${pwfile}
+    fi
+}
 
-		cp "$pwfile" "${submit_dir}"
-
-        if [ "$batch_option" = condor ]
+set_up_input_files()
+{
+    sep=""
+    for file in ${input_files}
+    do
+        if ! cp ${file} ${submit_dir}
         then
-		    condor_set_up_password_file
+			echo "Could not copy $file to $submit_dir" 1>&2
+			echo "Please check that the file exists and that the targe directory has write permissions $submit_dir" 1>&2
+			exit 1
         fi
-	fi
+
+        condor_transfer_input_files="${condor_transfer_input_files}$sep$(basename ${file})"
+        sep=","
+    done
 }
 
 submit_workers_command()
@@ -754,7 +810,7 @@ submit_workers_command()
         "slurm")
             slurm_submit_workers_command
         ;;
-        "uge")
+        "uge"|"sge")
             uge_submit_workers_command
         ;;
         *)
