Fix up cleanup/setup scripts to create a config file which is given on the command line.

diff --git a/batch_job/src/makeflow_ec2_cleanup b/batch_job/src/makeflow_ec2_cleanup
--- a/batch_job/src/makeflow_ec2_cleanup
+++ b/batch_job/src/makeflow_ec2_cleanup
@@ -1,13 +1,38 @@
 #!/bin/sh
 
-source ./amazon.config
+if [ "$#" -ne 1 ]; then
+	echo "use: $0 <config-file>"
+	exit 1
+fi
 
-echo "Deleting keypair $EC2_KEYPAIR_NAME..."
-aws ec2 delete-key-pair --key-name $EC2_KEYPAIR_NAME
-rm $EC2_KEYPAIR_NAME.pem
+configFile=$1
 
-echo "Deleting security group $EC2_SECURITY_GROUP..."
-aws ec2 delete-security-group --group-id $EC2_SECURITY_GROUP
+echo "Loading config file $config..."
+if [ ! -f $configFile ]
+then
+	echo "$0: config file $configFile not found"
+	exit 1
+fi
+
+security_group_id=$(python -c "import json; print json.load(open('$configFile','r'))['security_group_id'];")
+keypair_name=$(python -c "import json; print json.load(open('$configFile','r'))['keypair_name'];")
+
+echo -n "Checking for aws command in PATH..."
+if which aws >/dev/null 2>&1
+then
+        echo "ok"
+else
+        echo "failed"
+        echo "$0: \"aws\" command must be in your path to use this script."
+        exit 1
+fi
+
+echo "Deleting keypair $keypair_name..."
+aws ec2 delete-key-pair --key-name $keypair_name
+rm -f $keypair_name.pem
+
+echo "Deleting security group $security_group..."
+aws ec2 delete-security-group --group-id $security_group_id
 
 #echo "Deleting subnet $EC2_SUBNET..."
 #aws ec2 delete-subnet --subnet-id $EC2_SUBNET
