rellocate using same lock as untar

diff --git a/python_environments/python_package_run b/python_environments/python_package_run
--- a/python_environments/python_package_run
+++ b/python_environments/python_package_run
@@ -201,6 +201,12 @@ then
         echo "python_package_run: could not uncompress environment: ${ENV_NAME}"
         exit 1
     fi
+
+    if ! ${UNPACK_TO}/bin/conda-unpack
+    then
+        echo "python_package_run: could not relocate environment: ${ENV_NAME}"
+        exit 1
+    fi
     /bin/touch "${UNPACK_TO}"/.python_package_run_expanded
 else
     if [[ "${PYTHON_PACKAGE_RUN_DEBUG}" = yes ]]
@@ -229,14 +235,6 @@ source "${UNPACK_TO}/bin/activate"
 if [ "$?" != 0 ]
 then
     errmsg "could not activate environment: ${ENV_NAME}"
-    exit 1
-fi
-
-logmsg relocating paths
-flock -w ${LOCK_WAIT} ${LOCKFILE} conda-unpack
-if [ "$?" != 0 ]
-then
-    errmsg "could not unpack environment: ${ENV_NAME}"
     exit 1
 fi
 
